// GENERATED by `bun run generate:natives` — do not edit by hand.
//
// The calling convention every native binding in `src/stdlib/*.es` must keep,
// written as TypeScript so `tsc` can check it. Each `*Natives` type is the
// shape the runtime module of that Namespace must have. The `$<Namespace>`
// assertions at the foot check each runtime module against it; the paired
// `$<Namespace>Absent` assertion forbids a runtime export for any Method that is
// implemented in Essence. Nothing imports this file, so its only effect is the
// type error a drifted native raises under `tsc`. Regenerate after changing a
// standard library signature; `src/tests/natives.spec.ts` fails when it drifts
// from the renderer.

import type { AlgebraicType } from "./Algebraic"
import type { BooleanType } from "./Boolean"
import type { IntegerType } from "./Integer"
import type { ListType } from "./List"
import type { NothingType } from "./Nothing"
import type { NumberType } from "./Number"
import type { OrderingType } from "./Ordering"
import type { RationalType } from "./Rational"
import type { RecordType } from "./Record"
import type { StringType } from "./String"
import type { TranscendentalType } from "./Transcendental"
import type { AnyType } from "./type"

type AssertNoEssenceExports<Module, Forbidden extends string> =
	Extract<keyof Module, Forbidden> extends never
		? true
		: ["a Method implemented in Essence must not be a runtime export", Extract<keyof Module, Forbidden>]

type ComparableConformance<Self extends AnyType> = {
	compareTo: (self: Self, argument1: Self) => OrderingType
}

type EquatableConformance<Self extends AnyType> = {
	is: (self: Self, argument1: Self) => BooleanType
	isNot: (self: Self, argument1: Self) => BooleanType
}

type PrintableConformance<Self extends AnyType> = {
	toString: (self: Self) => StringType
}

export type StringNatives = {
	// append(_: String) -> String
	append: (self: StringType, argument1: StringType) => StringType
	// splitOn(_: String) -> List<String>
	splitOn: (self: StringType, argument1: StringType) => ListType<StringType>
	// uppercased() -> String
	uppercased: (self: StringType) => StringType
	// lowercased() -> String
	lowercased: (self: StringType) => StringType
	// trimmedAtStart() -> String
	trimmedAtStart: (self: StringType) => StringType
	// trimmedAtEnd() -> String
	trimmedAtEnd: (self: StringType) => StringType
	// replaceEvery(_: String, with: String) -> String
	replaceEvery: (self: StringType, argument1: StringType, argument2: StringType) => StringType
	// compareTo(_: String) -> Ordering
	compareTo: (self: StringType, argument1: StringType) => OrderingType
}

export type BooleanNatives = {
	// negate() -> Boolean
	negate: (self: BooleanType) => BooleanType
	// is(_: Boolean) -> Boolean
	is: (self: BooleanType, argument1: BooleanType) => BooleanType
	// and(_: Boolean) -> Boolean
	and: (self: BooleanType, argument1: BooleanType) => BooleanType
	// or(_: Boolean) -> Boolean
	or: (self: BooleanType, argument1: BooleanType) => BooleanType
	// exclusiveOr(_: Boolean) -> Boolean
	exclusiveOr: (self: BooleanType, argument1: BooleanType) => BooleanType
	// toString() -> String
	toString: (self: BooleanType) => StringType
}

export type IntegerNatives = {
	// add(_: Integer) -> Integer
	add__overload$1: (self: IntegerType, argument1: IntegerType) => IntegerType
	// add(_: Rational) -> Rational
	add__overload$2: (self: IntegerType, argument1: RationalType) => RationalType
	// add(_: Algebraic) -> Algebraic
	add__overload$3: (self: IntegerType, argument1: AlgebraicType) => AlgebraicType
	// add(_: Transcendental) -> Transcendental
	add__overload$4: (self: IntegerType, argument1: TranscendentalType) => TranscendentalType
	// divideBy(_: Algebraic) -> Algebraic | Rational
	divideBy__overload$3: (self: IntegerType, argument1: AlgebraicType) => AlgebraicType | RationalType
	// multiplyWith(_: Integer) -> Integer
	multiplyWith__overload$1: (self: IntegerType, argument1: IntegerType) => IntegerType
	// multiplyWith(_: Rational) -> Rational
	multiplyWith__overload$2: (self: IntegerType, argument1: RationalType) => RationalType
	// multiplyWith(_: Algebraic) -> Algebraic | Rational
	multiplyWith__overload$3: (self: IntegerType, argument1: AlgebraicType) => AlgebraicType | RationalType
	// multiplyWith(_: Transcendental) -> Transcendental | Rational
	multiplyWith__overload$4: (self: IntegerType, argument1: TranscendentalType) => TranscendentalType | RationalType
	// isLessThan(_: Rational) -> Boolean
	isLessThan__overload$2: (self: IntegerType, argument1: RationalType) => BooleanType
	// isLessThanOrEqualTo(_: Rational) -> Boolean
	isLessThanOrEqualTo__overload$2: (self: IntegerType, argument1: RationalType) => BooleanType
	// isGreaterThan(_: Rational) -> Boolean
	isGreaterThan__overload$2: (self: IntegerType, argument1: RationalType) => BooleanType
	// isGreaterThanOrEqualTo(_: Rational) -> Boolean
	isGreaterThanOrEqualTo__overload$2: (self: IntegerType, argument1: RationalType) => BooleanType
	// squareRoot() -> Optional<Integer | Algebraic>
	squareRoot: (self: IntegerType) => IntegerType | AlgebraicType | NothingType
	// negated() -> Integer
	negated: (self: IntegerType) => IntegerType
	// remainderOf(dividingBy: Integer) -> Optional<Integer>
	remainderOf: (self: IntegerType, dividingBy: IntegerType) => IntegerType | NothingType
	// toThePowerOf(_: Integer) -> Optional<Integer | Rational>
	toThePowerOf: (self: IntegerType, argument1: IntegerType) => IntegerType | RationalType | NothingType
	// static parse(_: String) -> Optional<Integer>
	parse: (argument0: StringType) => IntegerType | NothingType
	// toString() -> String
	toString: (self: IntegerType) => StringType
}

export type RationalNatives = {
	// static of(_: Integer, over: Integer) -> Optional<Rational>
	of: (argument0: IntegerType, over: IntegerType) => RationalType | NothingType
	// add(_: Rational) -> Rational
	add__overload$1: (self: RationalType, argument1: RationalType) => RationalType
	// add(_: Integer) -> Rational
	add__overload$2: (self: RationalType, argument1: IntegerType) => RationalType
	// add(_: Algebraic) -> Algebraic
	add__overload$3: (self: RationalType, argument1: AlgebraicType) => AlgebraicType
	// add(_: Transcendental) -> Transcendental
	add__overload$4: (self: RationalType, argument1: TranscendentalType) => TranscendentalType
	// divideBy(_: Rational) -> Optional<Rational>
	divideBy__overload$1: (self: RationalType, argument1: RationalType) => RationalType | NothingType
	// divideBy(_: Integer) -> Optional<Rational>
	divideBy__overload$2: (self: RationalType, argument1: IntegerType) => RationalType | NothingType
	// divideBy(_: Algebraic) -> Algebraic | Rational
	divideBy__overload$3: (self: RationalType, argument1: AlgebraicType) => AlgebraicType | RationalType
	// multiplyWith(_: Rational) -> Rational
	multiplyWith__overload$1: (self: RationalType, argument1: RationalType) => RationalType
	// multiplyWith(_: Integer) -> Rational
	multiplyWith__overload$2: (self: RationalType, argument1: IntegerType) => RationalType
	// multiplyWith(_: Algebraic) -> Algebraic | Rational
	multiplyWith__overload$3: (self: RationalType, argument1: AlgebraicType) => AlgebraicType | RationalType
	// multiplyWith(_: Transcendental) -> Transcendental | Rational
	multiplyWith__overload$4: (self: RationalType, argument1: TranscendentalType) => TranscendentalType | RationalType
	// isLessThan(_: Integer) -> Boolean
	isLessThan__overload$2: (self: RationalType, argument1: IntegerType) => BooleanType
	// isLessThanOrEqualTo(_: Integer) -> Boolean
	isLessThanOrEqualTo__overload$2: (self: RationalType, argument1: IntegerType) => BooleanType
	// isGreaterThan(_: Integer) -> Boolean
	isGreaterThan__overload$2: (self: RationalType, argument1: IntegerType) => BooleanType
	// isGreaterThanOrEqualTo(_: Integer) -> Boolean
	isGreaterThanOrEqualTo__overload$2: (self: RationalType, argument1: IntegerType) => BooleanType
	// squareRoot() -> Optional<Rational | Algebraic>
	squareRoot: (self: RationalType) => RationalType | AlgebraicType | NothingType
	// numerator() -> Integer
	numerator: (self: RationalType) => IntegerType
	// denominator() -> Integer
	denominator: (self: RationalType) => IntegerType
	// rounded() -> Integer
	rounded: (self: RationalType) => IntegerType
	// truncated() -> Integer
	truncated: (self: RationalType) => IntegerType
	// toThePowerOf(_: Integer) -> Optional<Rational>
	toThePowerOf: (self: RationalType, argument1: IntegerType) => RationalType | NothingType
	// static parse(_: String) -> Optional<Rational>
	parse: (argument0: StringType) => RationalType | NothingType
	// toString() -> String
	toString__overload$1: (self: RationalType) => StringType
	// toString(formatAs: String) -> String
	toString__overload$2: (self: RationalType, formatAs: StringType) => StringType
}

export type AlgebraicNatives = {
	// compareTo(_: Algebraic) -> Ordering
	compareTo: (self: AlgebraicType, argument1: AlgebraicType) => OrderingType
	// add(_: Integer) -> Algebraic
	add__overload$1: (self: AlgebraicType, argument1: IntegerType) => AlgebraicType
	// add(_: Rational) -> Algebraic
	add__overload$2: (self: AlgebraicType, argument1: RationalType) => AlgebraicType
	// add(_: Algebraic) -> Optional<Rational | Algebraic>
	add__overload$3: (self: AlgebraicType, argument1: AlgebraicType) => RationalType | AlgebraicType | NothingType
	// multiplyWith(_: Integer) -> Algebraic | Rational
	multiplyWith__overload$1: (self: AlgebraicType, argument1: IntegerType) => AlgebraicType | RationalType
	// multiplyWith(_: Rational) -> Algebraic | Rational
	multiplyWith__overload$2: (self: AlgebraicType, argument1: RationalType) => AlgebraicType | RationalType
	// multiplyWith(_: Algebraic) -> Optional<Rational | Algebraic>
	multiplyWith__overload$3: (self: AlgebraicType, argument1: AlgebraicType) => RationalType | AlgebraicType | NothingType
	// divideBy(_: Integer) -> Optional<Algebraic>
	divideBy__overload$1: (self: AlgebraicType, argument1: IntegerType) => AlgebraicType | NothingType
	// divideBy(_: Rational) -> Optional<Algebraic>
	divideBy__overload$2: (self: AlgebraicType, argument1: RationalType) => AlgebraicType | NothingType
	// divideBy(_: Algebraic) -> Optional<Rational | Algebraic>
	divideBy__overload$3: (self: AlgebraicType, argument1: AlgebraicType) => RationalType | AlgebraicType | NothingType
	// negated() -> Algebraic
	negated: (self: AlgebraicType) => AlgebraicType
	// toString() -> String
	toString: (self: AlgebraicType) => StringType
}

export type TranscendentalNatives = {
	// add(_: Integer) -> Transcendental
	add__overload$1: (self: TranscendentalType, argument1: IntegerType) => TranscendentalType
	// add(_: Rational) -> Transcendental
	add__overload$2: (self: TranscendentalType, argument1: RationalType) => TranscendentalType
	// add(_: Transcendental) -> Rational | Transcendental
	add__overload$3: (self: TranscendentalType, argument1: TranscendentalType) => RationalType | TranscendentalType
	// multiplyWith(_: Integer) -> Transcendental | Rational
	multiplyWith__overload$1: (self: TranscendentalType, argument1: IntegerType) => TranscendentalType | RationalType
	// multiplyWith(_: Rational) -> Transcendental | Rational
	multiplyWith__overload$2: (self: TranscendentalType, argument1: RationalType) => TranscendentalType | RationalType
	// divideBy(_: Integer) -> Optional<Transcendental>
	divideBy__overload$1: (self: TranscendentalType, argument1: IntegerType) => TranscendentalType | NothingType
	// divideBy(_: Rational) -> Optional<Transcendental>
	divideBy__overload$2: (self: TranscendentalType, argument1: RationalType) => TranscendentalType | NothingType
	// divideBy(_: Transcendental) -> Optional<Rational>
	divideBy__overload$3: (self: TranscendentalType, argument1: TranscendentalType) => RationalType | NothingType
	// negated() -> Transcendental
	negated: (self: TranscendentalType) => TranscendentalType
	// toString() -> String
	toString: (self: TranscendentalType) => StringType
}

export type NumberNatives = {
	// PI: Transcendental
	PI: TranscendentalType
	// TAU: Transcendental
	TAU: TranscendentalType
	// compareTo(_: Number) -> Ordering
	compareTo: (self: NumberType, argument1: NumberType) => OrderingType
	// static sum(_: List<Integer>) -> Integer
	sum__overload$1: (argument0: ListType<IntegerType>) => IntegerType
	// static sum(_: List<Rational>) -> Rational
	sum__overload$2: (argument0: ListType<RationalType>) => RationalType
	// static sum(_: List<Integer | Rational>) -> Integer | Rational
	sum__overload$3: (argument0: ListType<IntegerType | RationalType>) => IntegerType | RationalType
	// static product(_: List<Integer>) -> Integer
	product__overload$1: (argument0: ListType<IntegerType>) => IntegerType
	// static product(_: List<Rational>) -> Rational
	product__overload$2: (argument0: ListType<RationalType>) => RationalType
	// static product(_: List<Integer | Rational>) -> Integer | Rational
	product__overload$3: (argument0: ListType<IntegerType | RationalType>) => IntegerType | RationalType
	// static average(_: List<Integer>) -> Optional<Rational>
	average__overload$1: (argument0: ListType<IntegerType>) => RationalType | NothingType
	// static average(_: List<Rational>) -> Optional<Rational>
	average__overload$2: (argument0: ListType<RationalType>) => RationalType | NothingType
	// static average(_: List<Integer | Rational>) -> Optional<Rational>
	average__overload$3: (argument0: ListType<IntegerType | RationalType>) => RationalType | NothingType
	// static lowestNumber(_: List<Integer>) -> Optional<Integer>
	lowestNumber__overload$5: (argument0: ListType<IntegerType>) => IntegerType | NothingType
	// static lowestNumber(_: List<Rational>) -> Optional<Rational>
	lowestNumber__overload$6: (argument0: ListType<RationalType>) => RationalType | NothingType
	// static lowestNumber(_: List<Integer | Rational>) -> Optional<Integer | Rational>
	lowestNumber__overload$7: (argument0: ListType<IntegerType | RationalType>) => IntegerType | RationalType | NothingType
	// static greatestNumber(_: List<Integer>) -> Optional<Integer>
	greatestNumber__overload$5: (argument0: ListType<IntegerType>) => IntegerType | NothingType
	// static greatestNumber(_: List<Rational>) -> Optional<Rational>
	greatestNumber__overload$6: (argument0: ListType<RationalType>) => RationalType | NothingType
	// static greatestNumber(_: List<Integer | Rational>) -> Optional<Integer | Rational>
	greatestNumber__overload$7: (argument0: ListType<IntegerType | RationalType>) => IntegerType | RationalType | NothingType
}

export type NothingNatives = {

}

export type OptionalNatives = {

}

export type OrderingNatives = {

}

export type RecordNatives = {
	// is(_: Record) -> Boolean
	is: (self: RecordType, argument1: RecordType) => BooleanType
	// keys() -> List<String>
	keys: (self: RecordType) => ListType<StringType>
	// toString() -> String
	toString: (self: RecordType) => StringType
}

export type ListNatives = {
	// is<ItemType is Equatable>(_: List<ItemType>) -> Boolean
	is: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ListType<ItemType>, ItemType__conformance: EquatableConformance<ItemType>) => BooleanType
	// toString<ItemType>() -> String
	toString: <ItemType extends AnyType>(self: ListType<ItemType>) => StringType
	// length<ItemType>() -> Integer
	length: <ItemType extends AnyType>(self: ListType<ItemType>) => IntegerType
	// append<ItemType>(contentsOf: List<ItemType>) -> List<ItemType>
	append__overload$2: <ItemType extends AnyType>(self: ListType<ItemType>, contentsOf: ListType<ItemType>) => ListType<ItemType>
	// map<ItemType, Result>(_: (_: ItemType) -> Result) -> List<Result>
	map: <ItemType extends AnyType, Result extends AnyType>(self: ListType<ItemType>, argument1: (argument0: ItemType) => Result) => ListType<Result>
	// reduce<ItemType, Result>(startingWith: Result, _: (_: Result, _: ItemType) -> Result) -> Result
	reduce: <ItemType extends AnyType, Result extends AnyType>(self: ListType<ItemType>, startingWith: Result, argument2: (argument0: Result, argument1: ItemType) => Result) => Result
	// keepEvery<ItemType>(where: (_: ItemType) -> Boolean) -> List<ItemType>
	keepEvery: <ItemType extends AnyType>(self: ListType<ItemType>, where: (argument0: ItemType) => BooleanType) => ListType<ItemType>
	// itemAt<ItemType>(_: Integer) -> Optional<ItemType>
	itemAt: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: IntegerType) => ItemType | NothingType
	// firstIndexOf<ItemType is Equatable>(_: ItemType) -> Optional<Integer>
	firstIndexOf: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ItemType, ItemType__conformance: EquatableConformance<ItemType>) => IntegerType | NothingType
	// slice<ItemType>(from: Integer, to: Integer) -> List<ItemType>
	slice: <ItemType extends AnyType>(self: ListType<ItemType>, from: IntegerType, to: IntegerType) => ListType<ItemType>
	// reversed<ItemType>() -> List<ItemType>
	reversed: <ItemType extends AnyType>(self: ListType<ItemType>) => ListType<ItemType>
	// sortedBy<ItemType>(_: (_: ItemType, _: ItemType) -> Ordering) -> List<ItemType>
	sortedBy: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: (argument0: ItemType, argument1: ItemType) => OrderingType) => ListType<ItemType>
	// compareTo<ItemType is Comparable>(_: List<ItemType>) -> Ordering
	compareTo: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ListType<ItemType>, ItemType__conformance: ComparableConformance<ItemType>) => OrderingType
	// lastIndexOf<ItemType is Equatable>(_: ItemType) -> Optional<Integer>
	lastIndexOf: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ItemType, ItemType__conformance: EquatableConformance<ItemType>) => IntegerType | NothingType
	// joinWith<ItemType is Printable>(_: String) -> String
	joinWith: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: StringType, ItemType__conformance: PrintableConformance<ItemType>) => StringType
	// pairedWith<ItemType, Other>(_: List<Other>) -> List<{ first: ItemType, second: Other }>
	pairedWith: <ItemType extends AnyType, Other extends AnyType>(self: ListType<ItemType>, argument1: ListType<Other>) => ListType<RecordType & { first: ItemType; second: Other }>
	// splitInto<ItemType>(groupsOf: Integer) -> Optional<List<List<ItemType>>>
	splitInto: <ItemType extends AnyType>(self: ListType<ItemType>, groupsOf: IntegerType) => ListType<ListType<ItemType>> | NothingType
	// static of(integersFrom: Integer, through: Integer) -> List<Integer>
	of: (integersFrom: IntegerType, through: IntegerType) => ListType<IntegerType>
}

export type NestedListNatives = {
	// flattened<ItemType>() -> List<ItemType>
	flattened: <ItemType extends AnyType>(self: ListType<ListType<ItemType>>) => ListType<ItemType>
}

declare const StringModule: typeof import("./String")
export const $String: StringNatives = StringModule
export const $StringAbsent: AssertNoEssenceExports<typeof import("./String"), "isEmpty" | "hasAnyContent" | "is" | "isNot" | "prepend" | "contains" | "doesNotContain" | "length" | "characters" | "characterAt" | "trimmed" | "startsWith" | "doesNotStartWith" | "endsWith" | "doesNotEndWith" | "repeated" | "reversed" | "slice" | "firstIndexOf" | "paddedAtStart" | "paddedAtEnd" | "toString"> = true

declare const BooleanModule: typeof import("./Boolean")
export const $Boolean: BooleanNatives = BooleanModule
export const $BooleanAbsent: AssertNoEssenceExports<typeof import("./Boolean"), "isNot"> = true

declare const IntegerModule: typeof import("./Integer")
export const $Integer: IntegerNatives = IntegerModule
export const $IntegerAbsent: AssertNoEssenceExports<typeof import("./Integer"), "is" | "isNot" | "subtract__overload$1" | "subtract__overload$2" | "subtract__overload$3" | "subtract__overload$4" | "divideBy__overload$1" | "divideBy__overload$2" | "isLessThan__overload$1" | "isLessThanOrEqualTo__overload$1" | "isGreaterThan__overload$1" | "isGreaterThanOrEqualTo__overload$1" | "absolute" | "isEven" | "isOdd" | "isPositive" | "isNegative" | "isZero" | "clampedBetween" | "compareTo"> = true

declare const RationalModule: typeof import("./Rational")
export const $Rational: RationalNatives = RationalModule
export const $RationalAbsent: AssertNoEssenceExports<typeof import("./Rational"), "is" | "isNot" | "subtract__overload$1" | "subtract__overload$2" | "subtract__overload$3" | "subtract__overload$4" | "isLessThan__overload$1" | "isLessThanOrEqualTo__overload$1" | "isGreaterThan__overload$1" | "isGreaterThanOrEqualTo__overload$1" | "absolute" | "negated" | "reciprocal" | "isWholeNumber" | "roundedDown" | "roundedUp" | "compareTo"> = true

declare const AlgebraicModule: typeof import("./Algebraic")
export const $Algebraic: AlgebraicNatives = AlgebraicModule
export const $AlgebraicAbsent: AssertNoEssenceExports<typeof import("./Algebraic"), "is" | "isNot" | "subtract__overload$1" | "subtract__overload$2" | "subtract__overload$3" | "absolute"> = true

declare const TranscendentalModule: typeof import("./Transcendental")
export const $Transcendental: TranscendentalNatives = TranscendentalModule
export const $TranscendentalAbsent: AssertNoEssenceExports<typeof import("./Transcendental"), "is" | "isNot" | "subtract__overload$1" | "subtract__overload$2" | "subtract__overload$3" | "absolute"> = true

declare const NumberModule: typeof import("./Number")
export const $Number: NumberNatives = NumberModule
export const $NumberAbsent: AssertNoEssenceExports<typeof import("./Number"), "is" | "isNot" | "toString" | "isLessThan" | "isLessThanOrEqualTo" | "isGreaterThan" | "isGreaterThanOrEqualTo" | "isBetween" | "lowestNumber__overload$1" | "lowestNumber__overload$2" | "lowestNumber__overload$3" | "lowestNumber__overload$4" | "greatestNumber__overload$1" | "greatestNumber__overload$2" | "greatestNumber__overload$3" | "greatestNumber__overload$4"> = true

declare const NothingModule: typeof import("./Nothing")
export const $Nothing: NothingNatives = NothingModule
export const $NothingAbsent: AssertNoEssenceExports<typeof import("./Nothing"), "is" | "isNot" | "toString"> = true

declare const OptionalModule: typeof import("./Optional")
export const $Optional: OptionalNatives = OptionalModule
export const $OptionalAbsent: AssertNoEssenceExports<typeof import("./Optional"), "otherwise"> = true

declare const OrderingModule: typeof import("./Ordering")
export const $Ordering: OrderingNatives = OrderingModule
export const $OrderingAbsent: AssertNoEssenceExports<typeof import("./Ordering"), "is" | "isNot" | "toString"> = true

declare const RecordModule: typeof import("./Record")
export const $Record: RecordNatives = RecordModule
export const $RecordAbsent: AssertNoEssenceExports<typeof import("./Record"), "isNot"> = true

declare const ListModule: typeof import("./List")
export const $List: ListNatives = ListModule
export const $ListAbsent: AssertNoEssenceExports<typeof import("./List"), "isNot" | "hasItems" | "isEmpty" | "contains" | "doesNotContain" | "firstItem__overload$1" | "firstItem__overload$2" | "lastItem" | "removeFirst__overload$1" | "removeFirst__overload$2" | "removeAt" | "removeEvery__overload$1" | "removeEvery__overload$2" | "removeLast__overload$1" | "removeLast__overload$2" | "removeDuplicates" | "prepend__overload$1" | "prepend__overload$2" | "append__overload$1" | "sorted" | "anyItem" | "everyItem" | "countOf__overload$1" | "countOf__overload$2" | "insertAt" | "replaceAt" | "partitioned" | "repeating"> = true

declare const NestedListModule: typeof import("./NestedList")
export const $NestedList: NestedListNatives = NestedListModule
