// GENERATED by `bun run generate:natives` — do not edit by hand.
//
// The calling convention every native binding in `packages/standard-library/sources/*.es` must keep,
// written as TypeScript so `tsc` can check it. Each `*Natives` type is the
// shape the runtime module of that Namespace must have. The `$<Namespace>`
// assertions at the foot check each runtime module against it; the paired
// `$<Namespace>Absent` assertion forbids a runtime export for any Method that is
// implemented in Essence, and `$<Namespace>Arity` pins how many Parameters each
// native takes. Nothing imports this file, so its only effect is the
// type error a drifted native raises under `tsc`. Regenerate after changing a
// standard library signature; `src/tests/natives.spec.ts` fails when it drifts
// from the renderer.

import type { AlgebraicType } from "./Algebraic"
import type { BooleanType } from "./Boolean"
import type { IntegerType } from "./Integer"
import type { ListType } from "./List"
import type { NormalizationFormType } from "./NormalizationForm"
import type { NumberType } from "./Number"
import type { NumberFormatType } from "./NumberFormat"
import type { OptionalType } from "./Optional"
import type { OrderingType } from "./Ordering"
import type { RationalType } from "./Rational"
import type { RecordType } from "./Record"
import type { SideType } from "./Side"
import type { StepType } from "./Step"
import type { StreamType } from "./Stream"
import type { StringType } from "./String"
import type { TranscendentalType } from "./Transcendental"
import type { AnyType } from "./type"

type AssertNoEssenceExports<Module, Forbidden extends string> =
	Extract<keyof Module, Forbidden> extends never
		? true
		: ["a Method implemented in Essence must not be a runtime export", Extract<keyof Module, Forbidden>]

type NativeArity<Member> = Member extends (...args: infer Arguments) => unknown
	? Arguments["length"]
	: never

type MismatchedArities<Module, Arities extends Record<string, number>> = {
	[Member in keyof Arities & keyof Module]: NativeArity<Module[Member]> extends Arities[Member]
		? never
		: Member
}[keyof Arities & keyof Module]

type AssertArities<Module, Arities extends Record<string, number>> =
	MismatchedArities<Module, Arities> extends never
		? true
		: ["a native must take exactly the Parameters its declaration does, with no default or rest Parameter", MismatchedArities<Module, Arities>]

type ComparableConformance<Self extends AnyType> = {
	compare: (self: Self, to: Self) => OrderingType
}

type EquatableConformance<Self extends AnyType> = {
	is: (self: Self, argument1: Self) => BooleanType
	isNot: (self: Self, argument1: Self) => BooleanType
}

type PrintableConformance<Self extends AnyType> = {
	toString: (self: Self) => StringType
}

export type TerminalNatives = {
	// static write(_: String, to: Stream) -> Record
	write__overload$2: (argument0: StringType, to: StreamType) => RecordType
	// static inspect<Value>(_: Value) -> Value
	inspect: <Value extends AnyType>(argument0: Value) => Value
}

export type StringNatives = {
	// append(_: String) -> String
	append: (self: StringType, argument1: StringType) => StringType
	// split(on: String) -> List<String>
	split: (self: StringType, on: StringType) => ListType<StringType>
	// words() -> List<String>
	words: (self: StringType) => ListType<StringType>
	// length() -> Integer
	length: (self: StringType) => IntegerType
	// character(at: Integer) -> Optional<String>
	character: (self: StringType, at: IntegerType) => OptionalType<StringType>
	// uppercase() -> String
	uppercase: (self: StringType) => StringType
	// lowercase() -> String
	lowercase: (self: StringType) => StringType
	// normalize(as: NormalizationForm) -> String
	normalize__overload$2: (self: StringType, as: NormalizationFormType) => StringType
	// trim(at: Side) -> String
	trim__overload$2: (self: StringType, at: SideType) => StringType
	// ends(with: String) -> Boolean
	ends: (self: StringType, argument1: StringType) => BooleanType
	// repeat(times: Integer) -> String
	repeat: (self: StringType, times: IntegerType) => StringType
	// reverse() -> String
	reverse: (self: StringType) => StringType
	// slice(from: Integer, to: Integer) -> String
	slice: (self: StringType, from: IntegerType, to: IntegerType) => StringType
	// compare(to: String) -> Ordering
	compare__overload$1: (self: StringType, to: StringType) => OrderingType
}

export type BooleanNatives = {
	// negate() -> Boolean
	negate: (self: BooleanType) => BooleanType
	// is(_: Boolean) -> Boolean
	is: (self: BooleanType, argument1: BooleanType) => BooleanType
	// and(_: Boolean) -> Boolean
	and: (self: BooleanType, argument1: BooleanType) => BooleanType
	// or(_: Boolean) -> Boolean
	or: (self: BooleanType, argument1: BooleanType) => BooleanType
}

export type IntegerNatives = {
	// add(_: Integer) -> Integer
	add__overload$1: (self: IntegerType, argument1: IntegerType) => IntegerType
	// divide(by: Algebraic) -> Algebraic | Rational
	divide__overload$3: (self: IntegerType, by: AlgebraicType) => AlgebraicType | RationalType
	// divide(by: NonZeroInteger) -> Rational
	divide__overload$4: (self: IntegerType, by: IntegerType) => RationalType
	// multiply(with: Integer) -> Integer
	multiply__overload$1: (self: IntegerType, argument1: IntegerType) => IntegerType
	// squareRoot() -> Optional<Integer | Algebraic>
	squareRoot: (self: IntegerType) => OptionalType<IntegerType | AlgebraicType>
	// negate() -> Integer
	negate: (self: IntegerType) => IntegerType
	// remainder(dividingBy: Integer) -> Optional<Integer>
	remainder__overload$1: (self: IntegerType, dividingBy: IntegerType) => OptionalType<IntegerType>
	// remainder(dividingBy: NonZeroInteger) -> Integer
	remainder__overload$2: (self: IntegerType, dividingBy: IntegerType) => IntegerType
	// quotient(dividingBy: Integer) -> Optional<Integer>
	quotient__overload$1: (self: IntegerType, dividingBy: IntegerType) => OptionalType<IntegerType>
	// quotient(dividingBy: NonZeroInteger) -> Integer
	quotient__overload$2: (self: IntegerType, dividingBy: IntegerType) => IntegerType
	// raise(to: Integer) -> Optional<Integer | Rational>
	raise: (self: IntegerType, to: IntegerType) => OptionalType<IntegerType | RationalType>
	// toString() -> String
	toString: (self: IntegerType) => StringType
	// compare(to: Integer) -> Ordering
	compare: (self: IntegerType, to: IntegerType) => OrderingType
}

export type NonZeroIntegerNatives = {
	// multiply(with: NonZeroInteger) -> NonZeroInteger
	multiply: (self: IntegerType, argument1: IntegerType) => IntegerType
}

export type RationalNatives = {
	// static of(_: Integer, over: Integer) -> Optional<Rational>
	of__overload$1: (argument0: IntegerType, over: IntegerType) => OptionalType<RationalType>
	// static of(_: Integer, over: NonZeroInteger) -> Rational
	of__overload$2: (argument0: IntegerType, over: IntegerType) => RationalType
	// add(_: Rational) -> Rational
	add__overload$1: (self: RationalType, argument1: RationalType) => RationalType
	// subtract(_: Rational) -> Rational
	subtract__overload$1: (self: RationalType, argument1: RationalType) => RationalType
	// divide(by: Rational) -> Optional<Rational>
	divide__overload$1: (self: RationalType, by: RationalType) => OptionalType<RationalType>
	// divide(by: Algebraic) -> Algebraic | Rational
	divide__overload$3: (self: RationalType, by: AlgebraicType) => AlgebraicType | RationalType
	// multiply(with: Rational) -> Rational
	multiply__overload$1: (self: RationalType, argument1: RationalType) => RationalType
	// squareRoot() -> Optional<Rational | Algebraic>
	squareRoot: (self: RationalType) => OptionalType<RationalType | AlgebraicType>
	// numerator() -> Integer
	numerator: (self: RationalType) => IntegerType
	// denominator() -> NonZeroInteger
	denominator: (self: RationalType) => IntegerType
	// raise(to: Integer) -> Optional<Rational>
	raise: (self: RationalType, to: IntegerType) => OptionalType<RationalType>
	// toString(formatAs: NumberFormat) -> String
	toString__overload$2: (self: RationalType, formatAs: NumberFormatType) => StringType
	// compare(to: Rational) -> Ordering
	compare: (self: RationalType, to: RationalType) => OrderingType
}

export type AlgebraicNatives = {
	// compare(to: Algebraic) -> Ordering
	compare: (self: AlgebraicType, to: AlgebraicType) => OrderingType
	// add(_: Integer) -> Algebraic
	add__overload$1: (self: AlgebraicType, argument1: IntegerType) => AlgebraicType
	// add(_: Rational) -> Algebraic
	add__overload$2: (self: AlgebraicType, argument1: RationalType) => AlgebraicType
	// add(_: Algebraic) -> Optional<Rational | Algebraic>
	add__overload$3: (self: AlgebraicType, argument1: AlgebraicType) => OptionalType<RationalType | AlgebraicType>
	// multiply(with: Integer) -> Algebraic | Rational
	multiply__overload$1: (self: AlgebraicType, argument1: IntegerType) => AlgebraicType | RationalType
	// multiply(with: Rational) -> Algebraic | Rational
	multiply__overload$2: (self: AlgebraicType, argument1: RationalType) => AlgebraicType | RationalType
	// multiply(with: Algebraic) -> Optional<Rational | Algebraic>
	multiply__overload$3: (self: AlgebraicType, argument1: AlgebraicType) => OptionalType<RationalType | AlgebraicType>
	// divide(by: Integer) -> Optional<Algebraic>
	divide__overload$1: (self: AlgebraicType, by: IntegerType) => OptionalType<AlgebraicType>
	// divide(by: Rational) -> Optional<Algebraic>
	divide__overload$2: (self: AlgebraicType, by: RationalType) => OptionalType<AlgebraicType>
	// divide(by: Algebraic) -> Optional<Rational | Algebraic>
	divide__overload$3: (self: AlgebraicType, by: AlgebraicType) => OptionalType<RationalType | AlgebraicType>
	// negate() -> Algebraic
	negate: (self: AlgebraicType) => AlgebraicType
	// toString() -> String
	toString: (self: AlgebraicType) => StringType
}

export type TranscendentalNatives = {
	// is(_: Transcendental) -> Boolean
	is: (self: TranscendentalType, argument1: TranscendentalType) => BooleanType
	// add(_: Integer) -> Transcendental
	add__overload$1: (self: TranscendentalType, argument1: IntegerType) => TranscendentalType
	// add(_: Rational) -> Transcendental
	add__overload$2: (self: TranscendentalType, argument1: RationalType) => TranscendentalType
	// add(_: Transcendental) -> Rational | Transcendental
	add__overload$3: (self: TranscendentalType, argument1: TranscendentalType) => RationalType | TranscendentalType
	// multiply(with: Integer) -> Transcendental | Rational
	multiply__overload$1: (self: TranscendentalType, argument1: IntegerType) => TranscendentalType | RationalType
	// multiply(with: Rational) -> Transcendental | Rational
	multiply__overload$2: (self: TranscendentalType, argument1: RationalType) => TranscendentalType | RationalType
	// divide(by: Integer) -> Optional<Transcendental>
	divide__overload$1: (self: TranscendentalType, by: IntegerType) => OptionalType<TranscendentalType>
	// divide(by: Rational) -> Optional<Transcendental>
	divide__overload$2: (self: TranscendentalType, by: RationalType) => OptionalType<TranscendentalType>
	// divide(by: Transcendental) -> Optional<Rational>
	divide__overload$3: (self: TranscendentalType, by: TranscendentalType) => OptionalType<RationalType>
	// absolute() -> Transcendental
	absolute: (self: TranscendentalType) => TranscendentalType
	// negate() -> Transcendental
	negate: (self: TranscendentalType) => TranscendentalType
	// toString() -> String
	toString: (self: TranscendentalType) => StringType
}

export type NumberNatives = {
	// Pi: Transcendental
	Pi: TranscendentalType
	// Tau: Transcendental
	Tau: TranscendentalType
	// E: Transcendental
	E: TranscendentalType
	// GoldenRatio: Algebraic
	GoldenRatio: AlgebraicType
	// compare(to: Number) -> Ordering
	compare: (self: NumberType, to: NumberType) => OrderingType
}

export type OptionalNatives = {

}

export type NestedOptionalNatives = {

}

export type OrderingNatives = {

}

export type SideNatives = {

}

export type CaseNatives = {

}

export type NormalizationFormNatives = {

}

export type NumberFormatNatives = {

}

export type RoundingNatives = {

}

export type RecordNatives = {
	// is(_: Record) -> Boolean
	is: (self: RecordType, argument1: RecordType) => BooleanType
	// keys() -> List<String>
	keys: (self: RecordType) => ListType<StringType>
	// toString() -> String
	toString: (self: RecordType) => StringType
}

export type ListNatives = {
	// is<ItemType is Equatable>(_: List<ItemType>) -> Boolean
	is: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ListType<ItemType>, ItemType__conformance: EquatableConformance<ItemType>) => BooleanType
	// toString<ItemType is Printable>() -> String
	toString: <ItemType extends AnyType>(self: ListType<ItemType>, ItemType__conformance: PrintableConformance<ItemType>) => StringType
	// length<ItemType>() -> Integer
	length: <ItemType extends AnyType>(self: ListType<ItemType>) => IntegerType
	// remove<ItemType>(at: Integer) -> List<ItemType>
	remove: <ItemType extends AnyType>(self: ListType<ItemType>, at: IntegerType) => ListType<ItemType>
	// prepend<ItemType>(_: ItemType) -> NonEmptyList
	prepend__overload$1: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ItemType) => ListType<ItemType>
	// append<ItemType>(_: ItemType) -> NonEmptyList
	append__overload$1: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ItemType) => ListType<ItemType>
	// append<ItemType>(contentsOf: List<ItemType>) -> List<ItemType>
	append__overload$2: <ItemType extends AnyType>(self: ListType<ItemType>, contentsOf: ListType<ItemType>) => ListType<ItemType>
	// map<ItemType, Result>(_: (_: ItemType) -> Result) -> List<Result>
	map: <ItemType extends AnyType, Result extends AnyType>(self: ListType<ItemType>, argument1: (argument0: ItemType) => Result) => ListType<Result>
	// reduce<ItemType, Result>(startingWith: Result, _: (_: Result, _: ItemType) -> Result) -> Result
	reduce__overload$1: <ItemType extends AnyType, Result extends AnyType>(self: ListType<ItemType>, startingWith: Result, argument2: (argument0: Result, argument1: ItemType) => Result) => Result
	// reduce<ItemType, Result>(startingWith: Result, step: (_: Result, _: ItemType) -> Step<Result, Result>) -> Result
	reduce__overload$2: <ItemType extends AnyType, Result extends AnyType>(self: ListType<ItemType>, startingWith: Result, step: (argument0: Result, argument1: ItemType) => StepType<Result, Result>) => Result
	// keepEvery<ItemType>(where: (_: ItemType) -> Boolean) -> List<ItemType>
	keepEvery: <ItemType extends AnyType>(self: ListType<ItemType>, where: (argument0: ItemType) => BooleanType) => ListType<ItemType>
	// item<ItemType>(at: Integer) -> Optional<ItemType>
	item: <ItemType extends AnyType>(self: ListType<ItemType>, at: IntegerType) => OptionalType<ItemType>
	// slice<ItemType>(from: Integer, to: Integer) -> List<ItemType>
	slice: <ItemType extends AnyType>(self: ListType<ItemType>, from: IntegerType, to: IntegerType) => ListType<ItemType>
	// reverse<ItemType>() -> List<ItemType>
	reverse: <ItemType extends AnyType>(self: ListType<ItemType>) => ListType<ItemType>
	// sort<ItemType is Comparable>() -> List<ItemType>
	sort__overload$1: <ItemType extends AnyType>(self: ListType<ItemType>, ItemType__conformance: ComparableConformance<ItemType>) => ListType<ItemType>
	// sort<ItemType>(by: (_: ItemType, _: ItemType) -> Ordering) -> List<ItemType>
	sort__overload$2: <ItemType extends AnyType>(self: ListType<ItemType>, by: (argument0: ItemType, argument1: ItemType) => OrderingType) => ListType<ItemType>
	// compare<ItemType is Comparable>(to: List<ItemType>) -> Ordering
	compare: <ItemType extends AnyType>(self: ListType<ItemType>, to: ListType<ItemType>, ItemType__conformance: ComparableConformance<ItemType>) => OrderingType
	// insert<ItemType>(_: ItemType, at: Integer) -> NonEmptyList
	insert: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ItemType, at: IntegerType) => ListType<ItemType>
	// join<ItemType is Printable>(with: String) -> String
	join: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: StringType, ItemType__conformance: PrintableConformance<ItemType>) => StringType
	// pair<ItemType, Other>(with: List<Other>) -> List<{ first: ItemType, second: Other }>
	pair: <ItemType extends AnyType, Other extends AnyType>(self: ListType<ItemType>, argument1: ListType<Other>) => ListType<RecordType & { first: ItemType; second: Other }>
	// split<ItemType>(intoGroupsOf: Integer) -> Optional<List<List<ItemType>>>
	split: <ItemType extends AnyType>(self: ListType<ItemType>, intoGroupsOf: IntegerType) => OptionalType<ListType<ListType<ItemType>>>
	// static of(integersFrom: Integer, through: Integer) -> NonEmptyList
	of: (integersFrom: IntegerType, through: IntegerType) => ListType<IntegerType>
}

export type NestedListNatives = {
	// flatten<ItemType>() -> List<ItemType>
	flatten: <ItemType extends AnyType>(self: ListType<ListType<ItemType>>) => ListType<ItemType>
}

export type NonEmptyListNatives = {
	// firstItem<ItemType>() -> ItemType
	firstItem: <ItemType extends AnyType>(self: ListType<ItemType>) => ItemType
	// lastItem<ItemType>() -> ItemType
	lastItem: <ItemType extends AnyType>(self: ListType<ItemType>) => ItemType
	// removeDuplicates<ItemType is Equatable>() -> NonEmptyList
	removeDuplicates: <ItemType extends AnyType>(self: ListType<ItemType>, ItemType__conformance: EquatableConformance<ItemType>) => ListType<ItemType>
	// prepend<ItemType>(contentsOf: List<ItemType>) -> NonEmptyList
	prepend: <ItemType extends AnyType>(self: ListType<ItemType>, contentsOf: ListType<ItemType>) => ListType<ItemType>
	// append<ItemType>(contentsOf: List<ItemType>) -> NonEmptyList
	append: <ItemType extends AnyType>(self: ListType<ItemType>, contentsOf: ListType<ItemType>) => ListType<ItemType>
	// map<ItemType, Result>(_: (_: ItemType) -> Result) -> NonEmptyList
	map: <ItemType extends AnyType, Result extends AnyType>(self: ListType<ItemType>, argument1: (argument0: ItemType) => Result) => ListType<Result>
	// reverse<ItemType>() -> NonEmptyList
	reverse: <ItemType extends AnyType>(self: ListType<ItemType>) => ListType<ItemType>
	// sort<ItemType is Comparable>() -> NonEmptyList
	sort__overload$1: <ItemType extends AnyType>(self: ListType<ItemType>, ItemType__conformance: ComparableConformance<ItemType>) => ListType<ItemType>
	// sort<ItemType>(by: (_: ItemType, _: ItemType) -> Ordering) -> NonEmptyList
	sort__overload$2: <ItemType extends AnyType>(self: ListType<ItemType>, by: (argument0: ItemType, argument1: ItemType) => OrderingType) => ListType<ItemType>
	// replace<ItemType>(_: ItemType, at: Integer) -> NonEmptyList
	replace: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ItemType, at: IntegerType) => ListType<ItemType>
}

export type FunctionsNatives = {
	// static loop<State>(startingWith: State, while: (_: State) -> Boolean, step: (_: State) -> State) -> State
	loop__overload$1: <State extends AnyType>(startingWith: State, argument1: (argument0: State) => BooleanType, step: (argument0: State) => State) => State
	// static loop<State, Result>(startingWith: State, step: (_: State) -> Step<State, Result>) -> Result
	loop__overload$4: <State extends AnyType, Result extends AnyType>(startingWith: State, step: (argument0: State) => StepType<State, Result>) => Result
}

declare const TerminalModule: typeof import("./Terminal")
export const $Terminal: TerminalNatives = TerminalModule
export const $TerminalAbsent: AssertNoEssenceExports<typeof import("./Terminal"), "print__overload$1" | "print__overload$2" | "write__overload$1"> = true
export const $TerminalArity: AssertArities<typeof import("./Terminal"), {
	write__overload$2: 2
	inspect: 1
}> = true

declare const StringModule: typeof import("./String")
export const $String: StringNatives = StringModule
export const $StringAbsent: AssertNoEssenceExports<typeof import("./String"), "isEmpty" | "hasAnyContent" | "is__overload$1" | "is__overload$2" | "isNot" | "prepend" | "lines" | "contains" | "doesNotContain" | "characters" | "normalize__overload$1" | "trim__overload$1" | "starts" | "doesNotStart" | "doesNotEnd" | "replaceEvery" | "replaceFirst" | "firstIndex" | "lastIndex" | "pad__overload$1" | "pad__overload$2" | "compare__overload$2" | "toString"> = true
export const $StringArity: AssertArities<typeof import("./String"), {
	append: 2
	split: 2
	words: 1
	length: 1
	character: 2
	uppercase: 1
	lowercase: 1
	normalize__overload$2: 2
	trim__overload$2: 2
	ends: 2
	repeat: 2
	reverse: 1
	slice: 3
	compare__overload$1: 2
}> = true

declare const BooleanModule: typeof import("./Boolean")
export const $Boolean: BooleanNatives = BooleanModule
export const $BooleanAbsent: AssertNoEssenceExports<typeof import("./Boolean"), "isNot" | "exclusiveOr" | "toString"> = true
export const $BooleanArity: AssertArities<typeof import("./Boolean"), {
	negate: 1
	is: 2
	and: 2
	or: 2
}> = true

declare const IntegerModule: typeof import("./Integer")
export const $Integer: IntegerNatives = IntegerModule
export const $IntegerAbsent: AssertNoEssenceExports<typeof import("./Integer"), "is" | "isNot" | "add__overload$2" | "add__overload$3" | "add__overload$4" | "subtract__overload$1" | "subtract__overload$2" | "subtract__overload$3" | "subtract__overload$4" | "divide__overload$1" | "divide__overload$2" | "multiply__overload$2" | "multiply__overload$3" | "multiply__overload$4" | "isLessThan__overload$1" | "isLessThan__overload$2" | "isLessThanOrEqualTo__overload$1" | "isLessThanOrEqualTo__overload$2" | "isGreaterThan__overload$1" | "isGreaterThan__overload$2" | "isGreaterThanOrEqualTo__overload$1" | "isGreaterThanOrEqualTo__overload$2" | "absolute" | "isEven" | "isOdd" | "isPositive" | "isNegative" | "isZero" | "clamp" | "parse"> = true
export const $IntegerArity: AssertArities<typeof import("./Integer"), {
	add__overload$1: 2
	divide__overload$3: 2
	divide__overload$4: 2
	multiply__overload$1: 2
	squareRoot: 1
	negate: 1
	remainder__overload$1: 2
	remainder__overload$2: 2
	quotient__overload$1: 2
	quotient__overload$2: 2
	raise: 2
	toString: 1
	compare: 2
}> = true

declare const NonZeroIntegerModule: typeof import("./NonZeroInteger")
export const $NonZeroInteger: NonZeroIntegerNatives = NonZeroIntegerModule
export const $NonZeroIntegerArity: AssertArities<typeof import("./NonZeroInteger"), {
	multiply: 2
}> = true

declare const RationalModule: typeof import("./Rational")
export const $Rational: RationalNatives = RationalModule
export const $RationalAbsent: AssertNoEssenceExports<typeof import("./Rational"), "is" | "isNot" | "add__overload$2" | "add__overload$3" | "add__overload$4" | "subtract__overload$2" | "subtract__overload$3" | "subtract__overload$4" | "divide__overload$2" | "multiply__overload$2" | "multiply__overload$3" | "multiply__overload$4" | "isLessThan__overload$1" | "isLessThan__overload$2" | "isLessThanOrEqualTo__overload$1" | "isLessThanOrEqualTo__overload$2" | "isGreaterThan__overload$1" | "isGreaterThan__overload$2" | "isGreaterThanOrEqualTo__overload$1" | "isGreaterThanOrEqualTo__overload$2" | "absolute" | "negate" | "reciprocal" | "isWholeNumber" | "round__overload$1" | "round__overload$2" | "parse" | "toString__overload$1"> = true
export const $RationalArity: AssertArities<typeof import("./Rational"), {
	of__overload$1: 2
	of__overload$2: 2
	add__overload$1: 2
	subtract__overload$1: 2
	divide__overload$1: 2
	divide__overload$3: 2
	multiply__overload$1: 2
	squareRoot: 1
	numerator: 1
	denominator: 1
	raise: 2
	toString__overload$2: 2
	compare: 2
}> = true

declare const AlgebraicModule: typeof import("./Algebraic")
export const $Algebraic: AlgebraicNatives = AlgebraicModule
export const $AlgebraicAbsent: AssertNoEssenceExports<typeof import("./Algebraic"), "is" | "isNot" | "subtract__overload$1" | "subtract__overload$2" | "subtract__overload$3" | "absolute"> = true
export const $AlgebraicArity: AssertArities<typeof import("./Algebraic"), {
	compare: 2
	add__overload$1: 2
	add__overload$2: 2
	add__overload$3: 2
	multiply__overload$1: 2
	multiply__overload$2: 2
	multiply__overload$3: 2
	divide__overload$1: 2
	divide__overload$2: 2
	divide__overload$3: 2
	negate: 1
	toString: 1
}> = true

declare const TranscendentalModule: typeof import("./Transcendental")
export const $Transcendental: TranscendentalNatives = TranscendentalModule
export const $TranscendentalAbsent: AssertNoEssenceExports<typeof import("./Transcendental"), "isNot" | "subtract__overload$1" | "subtract__overload$2" | "subtract__overload$3"> = true
export const $TranscendentalArity: AssertArities<typeof import("./Transcendental"), {
	is: 2
	add__overload$1: 2
	add__overload$2: 2
	add__overload$3: 2
	multiply__overload$1: 2
	multiply__overload$2: 2
	divide__overload$1: 2
	divide__overload$2: 2
	divide__overload$3: 2
	absolute: 1
	negate: 1
	toString: 1
}> = true

declare const NumberModule: typeof import("./Number")
export const $Number: NumberNatives = NumberModule
export const $NumberAbsent: AssertNoEssenceExports<typeof import("./Number"), "is" | "isNot" | "toString" | "isLessThan" | "isLessThanOrEqualTo" | "isGreaterThan" | "isGreaterThanOrEqualTo" | "isBetween" | "sum__overload$1" | "sum__overload$2" | "sum__overload$3" | "product__overload$1" | "product__overload$2" | "product__overload$3" | "average__overload$1" | "average__overload$2" | "average__overload$3" | "lowestNumber__overload$1" | "lowestNumber__overload$2" | "lowestNumber__overload$3" | "lowestNumber__overload$4" | "lowestNumber__overload$5" | "lowestNumber__overload$6" | "lowestNumber__overload$7" | "greatestNumber__overload$1" | "greatestNumber__overload$2" | "greatestNumber__overload$3" | "greatestNumber__overload$4" | "greatestNumber__overload$5" | "greatestNumber__overload$6" | "greatestNumber__overload$7"> = true
export const $NumberArity: AssertArities<typeof import("./Number"), {
	compare: 2
}> = true

declare const OptionalModule: typeof import("./Optional")
export const $Optional: OptionalNatives = OptionalModule
export const $OptionalAbsent: AssertNoEssenceExports<typeof import("./Optional"), "toString" | "otherwise" | "hasValue" | "isEmpty" | "map" | "keep"> = true

declare const NestedOptionalModule: typeof import("./NestedOptional")
export const $NestedOptional: NestedOptionalNatives = NestedOptionalModule
export const $NestedOptionalAbsent: AssertNoEssenceExports<typeof import("./NestedOptional"), "flatten"> = true

declare const OrderingModule: typeof import("./Ordering")
export const $Ordering: OrderingNatives = OrderingModule
export const $OrderingAbsent: AssertNoEssenceExports<typeof import("./Ordering"), "toString"> = true

declare const SideModule: typeof import("./Side")
export const $Side: SideNatives = SideModule
export const $SideAbsent: AssertNoEssenceExports<typeof import("./Side"), "toString"> = true

declare const CaseModule: typeof import("./Case")
export const $Case: CaseNatives = CaseModule
export const $CaseAbsent: AssertNoEssenceExports<typeof import("./Case"), "toString"> = true

declare const NormalizationFormModule: typeof import("./NormalizationForm")
export const $NormalizationForm: NormalizationFormNatives = NormalizationFormModule
export const $NormalizationFormAbsent: AssertNoEssenceExports<typeof import("./NormalizationForm"), "toString"> = true

declare const NumberFormatModule: typeof import("./NumberFormat")
export const $NumberFormat: NumberFormatNatives = NumberFormatModule
export const $NumberFormatAbsent: AssertNoEssenceExports<typeof import("./NumberFormat"), "toString"> = true

declare const RoundingModule: typeof import("./Rounding")
export const $Rounding: RoundingNatives = RoundingModule
export const $RoundingAbsent: AssertNoEssenceExports<typeof import("./Rounding"), "toString"> = true

declare const RecordModule: typeof import("./Record")
export const $Record: RecordNatives = RecordModule
export const $RecordAbsent: AssertNoEssenceExports<typeof import("./Record"), "isNot"> = true
export const $RecordArity: AssertArities<typeof import("./Record"), {
	is: 2
	keys: 1
	toString: 1
}> = true

declare const ListModule: typeof import("./List")
export const $List: ListNatives = ListModule
export const $ListAbsent: AssertNoEssenceExports<typeof import("./List"), "isNot" | "hasItems" | "isEmpty" | "contains" | "doesNotContain" | "firstItem__overload$1" | "firstItem__overload$2" | "lastItem" | "removeFirst__overload$1" | "removeFirst__overload$2" | "removeEvery__overload$1" | "removeEvery__overload$2" | "removeLast__overload$1" | "removeLast__overload$2" | "removeDuplicates" | "prepend__overload$2" | "firstIndex" | "anyItem" | "everyItem" | "count__overload$1" | "count__overload$2" | "replace" | "lastIndex" | "partition" | "repeat"> = true
export const $ListArity: AssertArities<typeof import("./List"), {
	is: 3
	toString: 2
	length: 1
	remove: 2
	prepend__overload$1: 2
	append__overload$1: 2
	append__overload$2: 2
	map: 2
	reduce__overload$1: 3
	reduce__overload$2: 3
	keepEvery: 2
	item: 2
	slice: 3
	reverse: 1
	sort__overload$1: 2
	sort__overload$2: 2
	compare: 3
	insert: 3
	join: 3
	pair: 2
	split: 2
	of: 2
}> = true

declare const NestedListModule: typeof import("./NestedList")
export const $NestedList: NestedListNatives = NestedListModule
export const $NestedListArity: AssertArities<typeof import("./NestedList"), {
	flatten: 1
}> = true

declare const NonEmptyListModule: typeof import("./NonEmptyList")
export const $NonEmptyList: NonEmptyListNatives = NonEmptyListModule
export const $NonEmptyListArity: AssertArities<typeof import("./NonEmptyList"), {
	firstItem: 1
	lastItem: 1
	removeDuplicates: 2
	prepend: 2
	append: 2
	map: 2
	reverse: 1
	sort__overload$1: 2
	sort__overload$2: 2
	replace: 3
}> = true

declare const functionsModule: typeof import("./functions")
export const $functions: FunctionsNatives = functionsModule
export const $functionsAbsent: AssertNoEssenceExports<typeof import("./functions"), "loop__overload$2" | "loop__overload$3"> = true
export const $functionsArity: AssertArities<typeof import("./functions"), {
	loop__overload$1: 3
	loop__overload$4: 2
}> = true
