// GENERATED by `bun run generate:natives` — do not edit by hand.
//
// The calling convention every native binding in `packages/standard-library/sources/*.es` must keep,
// written as TypeScript so `tsc` can check it. Each `*Natives` type is the
// shape the runtime module of that Namespace must have. The `$<Namespace>`
// assertions at the foot check each runtime module against it; the paired
// `$<Namespace>Absent` assertion forbids a runtime export for any Method that is
// implemented in Essence, and `$<Namespace>Arity` pins how many Parameters each
// native takes. Nothing imports this file, so its only effect is the
// type error a drifted native raises under `tsc`. Regenerate after changing a
// standard library signature; `src/tests/natives.spec.ts` fails when it drifts
// from the renderer.

import type { AlgebraicType } from "./Algebraic"
import type { BooleanType } from "./Boolean"
import type { DictionaryType } from "./Dictionary"
import type { IntegerType } from "./Integer"
import type { ListType } from "./List"
import type { NormalizationFormType } from "./NormalizationForm"
import type { NumberType } from "./Number"
import type { NumberFormatType } from "./NumberFormat"
import type { OptionalType } from "./Optional"
import type { OrderingType } from "./Ordering"
import type { RandomnessType } from "./Randomness"
import type { RationalType } from "./Rational"
import type { RecordType } from "./Record"
import type { SideType } from "./Side"
import type { SortOrderType } from "./SortOrder"
import type { StepType } from "./Step"
import type { StreamType } from "./Stream"
import type { StringType } from "./String"
import type { TranscendentalType } from "./Transcendental"
import type { AnyType } from "./type"

type AssertNoEssenceExports<Module, Forbidden extends string> =
	Extract<keyof Module, Forbidden> extends never
		? true
		: ["a Method implemented in Essence must not be a runtime export", Extract<keyof Module, Forbidden>]

type NativeArity<Member> = Member extends (...args: infer Arguments) => unknown
	? Arguments["length"]
	: never

type MismatchedArities<Module, Arities extends Record<string, number>> = {
	[Member in keyof Arities & keyof Module]: NativeArity<Module[Member]> extends Arities[Member]
		? never
		: Member
}[keyof Arities & keyof Module]

type AssertArities<Module, Arities extends Record<string, number>> =
	MismatchedArities<Module, Arities> extends never
		? true
		: ["a native must take exactly the Parameters its declaration does, with no default or rest Parameter", MismatchedArities<Module, Arities>]

type ComparableConformance<Self extends AnyType> = {
	compare: (self: Self, to: Self) => OrderingType
}

type EquatableConformance<Self extends AnyType> = {
	is: (self: Self, argument1: Self) => BooleanType
	isNot: (self: Self, argument1: Self) => BooleanType
}

type PrintableConformance<Self extends AnyType> = {
	toString: (self: Self) => StringType
}

export type TerminalNatives = {
	// static write(_: String, to: Stream) -> Record
	write: (argument0: StringType, to: StreamType) => RecordType
	// static inspect<Value>(_: Value) -> Value
	inspect: <Value extends AnyType>(argument0: Value) => Value
	// static describe<Value>(_: Value) -> String
	describe: <Value extends AnyType>(argument0: Value) => StringType
}

export type StringNatives = {
	// compare(to: String) -> Ordering
	compare__overload$1: (self: StringType, to: StringType) => OrderingType
	// ends(with: String) -> Boolean
	ends: (self: StringType, argument1: StringType) => BooleanType
	// words() -> List<String>
	words: (self: StringType) => ListType<StringType>
	// length() -> NonNegativeInteger
	length: (self: StringType) => IntegerType
	// character(at: Integer) -> Optional<String>
	character__overload$1: (self: StringType, at: IntegerType) => OptionalType<StringType>
	// firstIndex(of: String) -> Optional<Integer>
	firstIndex__overload$1: (self: StringType, of: StringType) => OptionalType<IntegerType>
	// lastIndex(of: String) -> Optional<Integer>
	lastIndex__overload$1: (self: StringType, of: StringType) => OptionalType<IntegerType>
	// append(_: String) -> String
	append: (self: StringType, argument1: StringType) => StringType
	// split(on: String) -> List<String>
	split__overload$1: (self: StringType, on: StringType) => ListType<StringType>
	// split(on: NonEmptyString) -> NonEmptyList
	split__overload$2: (self: StringType, on: StringType) => ListType<StringType>
	// count(of: String) -> Integer
	count: (self: StringType, of: StringType) => IntegerType
	// uppercase() -> String
	uppercase: (self: StringType) => StringType
	// lowercase() -> String
	lowercase: (self: StringType) => StringType
	// normalize(as: NormalizationForm) -> String
	normalize: (self: StringType, as: NormalizationFormType) => StringType
	// trim(at: Side) -> String
	trim: (self: StringType, at: SideType) => StringType
	// repeat(times: Integer) -> String
	repeat: (self: StringType, times: IntegerType) => StringType
	// reverse() -> String
	reverse: (self: StringType) => StringType
	// slice(from: Integer, to: Integer) -> String
	slice: (self: StringType, from: IntegerType, to: IntegerType) => StringType
}

export type NonEmptyStringNatives = {
	// length() -> PositiveInteger
	length: (self: StringType) => IntegerType
	// characters() -> NonEmptyList
	characters: (self: StringType) => ListType<StringType>
	// firstCharacter() -> String
	firstCharacter: (self: StringType) => StringType
	// lastCharacter() -> String
	lastCharacter: (self: StringType) => StringType
	// uppercase() -> NonEmptyString
	uppercase: (self: StringType) => StringType
	// lowercase() -> NonEmptyString
	lowercase: (self: StringType) => StringType
	// reverse() -> NonEmptyString
	reverse: (self: StringType) => StringType
	// repeat(times: PositiveInteger) -> NonEmptyString
	repeat: (self: StringType, times: IntegerType) => StringType
}

export type BooleanNatives = {
	// is(_: Boolean) -> Boolean
	is: (self: BooleanType, argument1: BooleanType) => BooleanType
	// negate() -> Boolean
	negate: (self: BooleanType) => BooleanType
	// and(_: Boolean) -> Boolean
	and: (self: BooleanType, argument1: BooleanType) => BooleanType
	// or(_: Boolean) -> Boolean
	or: (self: BooleanType, argument1: BooleanType) => BooleanType
}

export type IntegerNatives = {
	// compare(to: Integer) -> Ordering
	compare: (self: IntegerType, to: IntegerType) => OrderingType
	// toString() -> String
	toString: (self: IntegerType) => StringType
	// add(_: Integer) -> Integer
	add__overload$1: (self: IntegerType, argument1: IntegerType) => IntegerType
	// multiply(with: Integer) -> Integer
	multiply__overload$1: (self: IntegerType, argument1: IntegerType) => IntegerType
	// divide(by: Algebraic) -> Algebraic | Rational
	divide__overload$3: (self: IntegerType, by: AlgebraicType) => AlgebraicType | RationalType
	// divide(by: NonZeroInteger) -> Rational
	divide__overload$4: (self: IntegerType, by: IntegerType) => RationalType
	// remainder(dividingBy: Integer) -> Optional<Integer>
	remainder__overload$1: (self: IntegerType, dividingBy: IntegerType) => OptionalType<IntegerType>
	// remainder(dividingBy: NonZeroInteger) -> Integer
	remainder__overload$2: (self: IntegerType, dividingBy: IntegerType) => IntegerType
	// quotient(dividingBy: Integer) -> Optional<Integer>
	quotient__overload$1: (self: IntegerType, dividingBy: IntegerType) => OptionalType<IntegerType>
	// quotient(dividingBy: NonZeroInteger) -> Integer
	quotient__overload$2: (self: IntegerType, dividingBy: IntegerType) => IntegerType
	// raise(to: Integer) -> Optional<Integer | Rational>
	raise__overload$1: (self: IntegerType, to: IntegerType) => OptionalType<IntegerType | RationalType>
	// raise(to: NonNegativeInteger) -> Integer
	raise__overload$3: (self: IntegerType, to: IntegerType) => IntegerType
	// squareRoot() -> Optional<Integer | Algebraic>
	squareRoot__overload$1: (self: IntegerType) => OptionalType<IntegerType | AlgebraicType>
	// absolute() -> NonNegativeInteger
	absolute: (self: IntegerType) => IntegerType
	// negate() -> Integer
	negate: (self: IntegerType) => IntegerType
}

export type NonZeroIntegerNatives = {
	// multiply(with: NonZeroInteger) -> NonZeroInteger
	multiply__overload$1: (self: IntegerType, argument1: IntegerType) => IntegerType
	// divide(by: NonZeroInteger) -> NonZeroRational
	divide: (self: IntegerType, by: IntegerType) => RationalType
	// raise(to: Integer) -> Integer | Rational
	raise__overload$1: (self: IntegerType, to: IntegerType) => IntegerType | RationalType
	// raise(to: NonNegativeInteger) -> Integer
	raise__overload$2: (self: IntegerType, to: IntegerType) => IntegerType
	// absolute() -> PositiveInteger
	absolute: (self: IntegerType) => IntegerType
	// negate() -> NonZeroInteger
	negate: (self: IntegerType) => IntegerType
}

export type NonNegativeIntegerNatives = {
	// add(_: PositiveInteger) -> PositiveInteger
	add__overload$1: (self: IntegerType, argument1: IntegerType) => IntegerType
	// add(_: NonNegativeInteger) -> NonNegativeInteger
	add__overload$2: (self: IntegerType, argument1: IntegerType) => IntegerType
	// multiply(with: NonNegativeInteger) -> NonNegativeInteger
	multiply: (self: IntegerType, argument1: IntegerType) => IntegerType
	// squareRoot() -> Integer | Algebraic
	squareRoot: (self: IntegerType) => IntegerType | AlgebraicType
}

export type PositiveIntegerNatives = {
	// add(_: NonNegativeInteger) -> PositiveInteger
	add: (self: IntegerType, argument1: IntegerType) => IntegerType
	// multiply(with: PositiveInteger) -> PositiveInteger
	multiply: (self: IntegerType, argument1: IntegerType) => IntegerType
	// raise(to: NonNegativeInteger) -> PositiveInteger
	raise: (self: IntegerType, to: IntegerType) => IntegerType
	// squareRoot() -> PositiveInteger | Algebraic
	squareRoot: (self: IntegerType) => IntegerType | AlgebraicType
}

export type RationalNatives = {
	// static of(_: Integer, over: Integer) -> Optional<Rational>
	of__overload$1: (argument0: IntegerType, over: IntegerType) => OptionalType<RationalType>
	// static of(_: Integer, over: NonZeroInteger) -> Rational
	of__overload$2: (argument0: IntegerType, over: IntegerType) => RationalType
	// compare(to: Rational) -> Ordering
	compare: (self: RationalType, to: RationalType) => OrderingType
	// toString(as: NumberFormat) -> String
	toString__overload$2: (self: RationalType, as: NumberFormatType) => StringType
	// toString(as: NumberFormat, places: Integer) -> String
	toString__overload$3: (self: RationalType, as: NumberFormatType, places: IntegerType) => StringType
	// add(_: Rational) -> Rational
	add__overload$1: (self: RationalType, argument1: RationalType) => RationalType
	// subtract(_: Rational) -> Rational
	subtract__overload$1: (self: RationalType, argument1: RationalType) => RationalType
	// multiply(with: Rational) -> Rational
	multiply__overload$1: (self: RationalType, argument1: RationalType) => RationalType
	// divide(by: Rational) -> Optional<Rational>
	divide__overload$1: (self: RationalType, by: RationalType) => OptionalType<RationalType>
	// divide(by: Algebraic) -> Algebraic | Rational
	divide__overload$3: (self: RationalType, by: AlgebraicType) => AlgebraicType | RationalType
	// divide(by: NonZeroRational) -> Rational
	divide__overload$7: (self: RationalType, by: RationalType) => RationalType
	// raise(to: Integer) -> Optional<Rational>
	raise__overload$1: (self: RationalType, to: IntegerType) => OptionalType<RationalType>
	// raise(to: NonNegativeInteger) -> Rational
	raise__overload$3: (self: RationalType, to: IntegerType) => RationalType
	// squareRoot() -> Optional<Rational | Algebraic>
	squareRoot__overload$1: (self: RationalType) => OptionalType<RationalType | AlgebraicType>
	// numerator() -> Integer
	numerator: (self: RationalType) => IntegerType
	// denominator() -> PositiveInteger
	denominator: (self: RationalType) => IntegerType
}

export type NonZeroRationalNatives = {
	// multiply(with: NonZeroRational) -> NonZeroRational
	multiply: (self: RationalType, argument1: RationalType) => RationalType
	// numerator() -> NonZeroInteger
	numerator: (self: RationalType) => IntegerType
	// reciprocal() -> NonZeroRational
	reciprocal: (self: RationalType) => RationalType
	// negate() -> NonZeroRational
	negate: (self: RationalType) => RationalType
}

export type ScalarNatives = {

}

export type AlgebraicNatives = {
	// compare(to: Algebraic) -> Ordering
	compare: (self: AlgebraicType, to: AlgebraicType) => OrderingType
	// toString() -> String
	toString: (self: AlgebraicType) => StringType
	// add(_: Integer) -> Algebraic
	add__overload$1: (self: AlgebraicType, argument1: IntegerType) => AlgebraicType
	// add(_: Rational) -> Algebraic
	add__overload$2: (self: AlgebraicType, argument1: RationalType) => AlgebraicType
	// add(_: Algebraic) -> Optional<Rational | Algebraic>
	add__overload$3: (self: AlgebraicType, argument1: AlgebraicType) => OptionalType<RationalType | AlgebraicType>
	// multiply(with: Integer) -> Algebraic | Rational
	multiply__overload$1: (self: AlgebraicType, argument1: IntegerType) => AlgebraicType | RationalType
	// multiply(with: Rational) -> Algebraic | Rational
	multiply__overload$2: (self: AlgebraicType, argument1: RationalType) => AlgebraicType | RationalType
	// multiply(with: Algebraic) -> Optional<Rational | Algebraic>
	multiply__overload$3: (self: AlgebraicType, argument1: AlgebraicType) => OptionalType<RationalType | AlgebraicType>
	// multiply(with: NonZeroInteger) -> Algebraic
	multiply__overload$5: (self: AlgebraicType, argument1: IntegerType) => AlgebraicType
	// multiply(with: NonZeroRational) -> Algebraic
	multiply__overload$6: (self: AlgebraicType, argument1: RationalType) => AlgebraicType
	// divide(by: Integer) -> Optional<Algebraic>
	divide__overload$1: (self: AlgebraicType, by: IntegerType) => OptionalType<AlgebraicType>
	// divide(by: Rational) -> Optional<Algebraic>
	divide__overload$2: (self: AlgebraicType, by: RationalType) => OptionalType<AlgebraicType>
	// divide(by: Algebraic) -> Optional<Rational | Algebraic>
	divide__overload$3: (self: AlgebraicType, by: AlgebraicType) => OptionalType<RationalType | AlgebraicType>
	// divide(by: NonZeroInteger) -> Algebraic
	divide__overload$7: (self: AlgebraicType, by: IntegerType) => AlgebraicType
	// divide(by: NonZeroRational) -> Algebraic
	divide__overload$8: (self: AlgebraicType, by: RationalType) => AlgebraicType
	// negate() -> Algebraic
	negate: (self: AlgebraicType) => AlgebraicType
}

export type TranscendentalNatives = {
	// is(_: Transcendental) -> Boolean
	is: (self: TranscendentalType, argument1: TranscendentalType) => BooleanType
	// compare(to: Transcendental, withPrecision: PositiveInteger) -> Optional<Ordering>
	compare: (self: TranscendentalType, to: TranscendentalType, withPrecision: IntegerType) => OptionalType<OrderingType>
	// toString() -> String
	toString: (self: TranscendentalType) => StringType
	// add(_: Integer) -> Transcendental
	add__overload$1: (self: TranscendentalType, argument1: IntegerType) => TranscendentalType
	// add(_: Rational) -> Transcendental
	add__overload$2: (self: TranscendentalType, argument1: RationalType) => TranscendentalType
	// add(_: Transcendental) -> Rational | Transcendental
	add__overload$3: (self: TranscendentalType, argument1: TranscendentalType) => RationalType | TranscendentalType
	// multiply(with: Integer) -> Transcendental | Rational
	multiply__overload$1: (self: TranscendentalType, argument1: IntegerType) => TranscendentalType | RationalType
	// multiply(with: Rational) -> Transcendental | Rational
	multiply__overload$2: (self: TranscendentalType, argument1: RationalType) => TranscendentalType | RationalType
	// multiply(with: NonZeroInteger) -> Transcendental
	multiply__overload$3: (self: TranscendentalType, argument1: IntegerType) => TranscendentalType
	// multiply(with: NonZeroRational) -> Transcendental
	multiply__overload$4: (self: TranscendentalType, argument1: RationalType) => TranscendentalType
	// divide(by: Integer) -> Optional<Transcendental>
	divide__overload$1: (self: TranscendentalType, by: IntegerType) => OptionalType<TranscendentalType>
	// divide(by: Rational) -> Optional<Transcendental>
	divide__overload$2: (self: TranscendentalType, by: RationalType) => OptionalType<TranscendentalType>
	// divide(by: Transcendental) -> Optional<Rational>
	divide__overload$3: (self: TranscendentalType, by: TranscendentalType) => OptionalType<RationalType>
	// divide(by: NonZeroInteger) -> Transcendental
	divide__overload$7: (self: TranscendentalType, by: IntegerType) => TranscendentalType
	// divide(by: NonZeroRational) -> Transcendental
	divide__overload$8: (self: TranscendentalType, by: RationalType) => TranscendentalType
	// absolute() -> Transcendental
	absolute: (self: TranscendentalType) => TranscendentalType
	// negate() -> Transcendental
	negate: (self: TranscendentalType) => TranscendentalType
}

export type NumberNatives = {
	// Pi: Transcendental
	Pi: TranscendentalType
	// Tau: Transcendental
	Tau: TranscendentalType
	// E: Transcendental
	E: TranscendentalType
	// GoldenRatio: Algebraic
	GoldenRatio: AlgebraicType
	// compare(to: Number) -> Ordering
	compare: (self: NumberType, to: NumberType) => OrderingType
}

export type OptionalNatives = {
	// toString<ItemType is Printable>() -> String
	toString: <ItemType extends AnyType>(self: OptionalType<ItemType>, ItemType__conformance: PrintableConformance<ItemType>) => StringType
}

export type NestedOptionalNatives = {

}

export type OrderingNatives = {

}

export type SideNatives = {

}

export type CaseSensitivityNatives = {

}

export type NormalizationFormNatives = {

}

export type NumberFormatNatives = {

}

export type RoundingNatives = {

}

export type SortOrderNatives = {

}

export type StreamNatives = {

}

export type RecordNatives = {
	// is(_: Record) -> Boolean
	is: (self: RecordType, argument1: RecordType) => BooleanType
	// toString() -> String
	toString: (self: RecordType) => StringType
	// keys() -> List<String>
	keys: (self: RecordType) => ListType<StringType>
}

export type ListNatives = {
	// static repeat<ItemType>(_: ItemType, times: PositiveInteger) -> NonEmptyList
	repeat__overload$2: <ItemType extends AnyType>(argument0: ItemType, times: IntegerType) => ListType<ItemType>
	// static of(integersFrom: Integer, through: Integer) -> NonEmptyList
	of__overload$1: (integersFrom: IntegerType, through: IntegerType) => ListType<IntegerType>
	// is<ItemType is Equatable>(_: List<ItemType>) -> Boolean
	is: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ListType<ItemType>, ItemType__conformance: EquatableConformance<ItemType>) => BooleanType
	// compare<ItemType is Comparable>(to: List<ItemType>) -> Ordering
	compare: <ItemType extends AnyType>(self: ListType<ItemType>, to: ListType<ItemType>, ItemType__conformance: ComparableConformance<ItemType>) => OrderingType
	// toString<ItemType is Printable>() -> String
	toString: <ItemType extends AnyType>(self: ListType<ItemType>, ItemType__conformance: PrintableConformance<ItemType>) => StringType
	// length<ItemType>() -> NonNegativeInteger
	length: <ItemType extends AnyType>(self: ListType<ItemType>) => IntegerType
	// item<ItemType>(at: Integer) -> Optional<ItemType>
	item__overload$1: <ItemType extends AnyType>(self: ListType<ItemType>, at: IntegerType) => OptionalType<ItemType>
	// lastIndex<ItemType>(where: (_: ItemType) -> Boolean) -> Optional<Integer>
	lastIndex__overload$3: <ItemType extends AnyType>(self: ListType<ItemType>, where: (argument0: ItemType) => BooleanType) => OptionalType<IntegerType>
	// enumerate<ItemType>() -> List<{ index: Integer, item: ItemType }>
	enumerate: <ItemType extends AnyType>(self: ListType<ItemType>) => ListType<RecordType & { index: IntegerType; item: ItemType }>
	// remove<ItemType>(at: Integer) -> List<ItemType>
	remove: <ItemType extends AnyType>(self: ListType<ItemType>, at: IntegerType) => ListType<ItemType>
	// prepend<ItemType>(_: ItemType) -> NonEmptyList
	prepend__overload$1: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ItemType) => ListType<ItemType>
	// append<ItemType>(_: ItemType) -> NonEmptyList
	append__overload$1: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ItemType) => ListType<ItemType>
	// append<ItemType>(contentsOf: List<ItemType>) -> List<ItemType>
	append__overload$2: <ItemType extends AnyType>(self: ListType<ItemType>, contentsOf: ListType<ItemType>) => ListType<ItemType>
	// map<ItemType, Result>(_: (_: ItemType) -> Result) -> List<Result>
	map: <ItemType extends AnyType, Result extends AnyType>(self: ListType<ItemType>, argument1: (argument0: ItemType) => Result) => ListType<Result>
	// reduce<ItemType, Result>(startingWith: Result, _: (_: Result, _: ItemType) -> Result) -> Result
	reduce__overload$1: <ItemType extends AnyType, Result extends AnyType>(self: ListType<ItemType>, startingWith: Result, argument2: (argument0: Result, argument1: ItemType) => Result) => Result
	// reduce<ItemType, Result>(startingWith: Result, step: (_: Result, _: ItemType) -> Step<Result, Result>) -> Result
	reduce__overload$2: <ItemType extends AnyType, Result extends AnyType>(self: ListType<ItemType>, startingWith: Result, step: (argument0: Result, argument1: ItemType) => StepType<Result, Result>) => Result
	// everyItem<ItemType>(where: (_: ItemType) -> Boolean) -> List<ItemType>
	everyItem: <ItemType extends AnyType>(self: ListType<ItemType>, where: (argument0: ItemType) => BooleanType) => ListType<ItemType>
	// slice<ItemType>(from: Integer, to: Integer) -> List<ItemType>
	slice: <ItemType extends AnyType>(self: ListType<ItemType>, from: IntegerType, to: IntegerType) => ListType<ItemType>
	// reverse<ItemType>() -> List<ItemType>
	reverse: <ItemType extends AnyType>(self: ListType<ItemType>) => ListType<ItemType>
	// sort<ItemType is Comparable>(in: SortOrder) -> List<ItemType>
	sort__overload$1: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: SortOrderType, ItemType__conformance: ComparableConformance<ItemType>) => ListType<ItemType>
	// sort<ItemType>(by: (_: ItemType, _: ItemType) -> Ordering) -> List<ItemType>
	sort__overload$2: <ItemType extends AnyType>(self: ListType<ItemType>, by: (argument0: ItemType, argument1: ItemType) => OrderingType) => ListType<ItemType>
	// sort<ItemType, Key is Comparable>(on: (_: ItemType) -> Key, in: SortOrder) -> List<ItemType>
	sort__overload$3: <ItemType extends AnyType, Key extends AnyType>(self: ListType<ItemType>, on: (argument0: ItemType) => Key, argument2: SortOrderType, Key__conformance: ComparableConformance<Key>) => ListType<ItemType>
	// insert<ItemType>(_: ItemType, at: Integer) -> NonEmptyList
	insert: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ItemType, at: IntegerType) => ListType<ItemType>
	// join<ItemType is Printable>(with: String) -> String
	join: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: StringType, ItemType__conformance: PrintableConformance<ItemType>) => StringType
	// partition<ItemType>(where: (_: ItemType) -> Boolean) -> { accepted: List<ItemType>, refused: List<ItemType> }
	partition: <ItemType extends AnyType>(self: ListType<ItemType>, where: (argument0: ItemType) => BooleanType) => RecordType & { accepted: ListType<ItemType>; refused: ListType<ItemType> }
	// pair<ItemType, Other>(with: List<Other>) -> List<{ first: ItemType, second: Other }>
	pair: <ItemType extends AnyType, Other extends AnyType>(self: ListType<ItemType>, argument1: ListType<Other>) => ListType<RecordType & { first: ItemType; second: Other }>
	// split<ItemType>(intoGroupsOf: Integer) -> List<NonEmptyList>
	split: <ItemType extends AnyType>(self: ListType<ItemType>, intoGroupsOf: IntegerType) => ListType<ListType<ItemType>>
}

export type NestedListNatives = {
	// flatten<ItemType>() -> List<ItemType>
	flatten: <ItemType extends AnyType>(self: ListType<ListType<ItemType>>) => ListType<ItemType>
}

export type OptionalListNatives = {

}

export type NonEmptyListNatives = {
	// firstItem<ItemType>() -> ItemType
	firstItem: <ItemType extends AnyType>(self: ListType<ItemType>) => ItemType
	// lastItem<ItemType>() -> ItemType
	lastItem: <ItemType extends AnyType>(self: ListType<ItemType>) => ItemType
	// length<ItemType>() -> PositiveInteger
	length: <ItemType extends AnyType>(self: ListType<ItemType>) => IntegerType
	// enumerate<ItemType>() -> NonEmptyList
	enumerate: <ItemType extends AnyType>(self: ListType<ItemType>) => ListType<RecordType & { index: IntegerType; item: ItemType }>
	// prepend<ItemType>(contentsOf: List<ItemType>) -> NonEmptyList
	prepend: <ItemType extends AnyType>(self: ListType<ItemType>, contentsOf: ListType<ItemType>) => ListType<ItemType>
	// append<ItemType>(contentsOf: List<ItemType>) -> NonEmptyList
	append: <ItemType extends AnyType>(self: ListType<ItemType>, contentsOf: ListType<ItemType>) => ListType<ItemType>
	// map<ItemType, Result>(_: (_: ItemType) -> Result) -> NonEmptyList
	map: <ItemType extends AnyType, Result extends AnyType>(self: ListType<ItemType>, argument1: (argument0: ItemType) => Result) => ListType<Result>
	// reverse<ItemType>() -> NonEmptyList
	reverse: <ItemType extends AnyType>(self: ListType<ItemType>) => ListType<ItemType>
	// sort<ItemType is Comparable>(in: SortOrder) -> NonEmptyList
	sort__overload$1: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: SortOrderType, ItemType__conformance: ComparableConformance<ItemType>) => ListType<ItemType>
	// sort<ItemType>(by: (_: ItemType, _: ItemType) -> Ordering) -> NonEmptyList
	sort__overload$2: <ItemType extends AnyType>(self: ListType<ItemType>, by: (argument0: ItemType, argument1: ItemType) => OrderingType) => ListType<ItemType>
	// sort<ItemType, Key is Comparable>(on: (_: ItemType) -> Key, in: SortOrder) -> NonEmptyList
	sort__overload$3: <ItemType extends AnyType, Key extends AnyType>(self: ListType<ItemType>, on: (argument0: ItemType) => Key, argument2: SortOrderType, Key__conformance: ComparableConformance<Key>) => ListType<ItemType>
	// replace<ItemType>(_: ItemType, at: Integer) -> NonEmptyList
	replace__overload$1: <ItemType extends AnyType>(self: ListType<ItemType>, argument1: ItemType, at: IntegerType) => ListType<ItemType>
	// pair<ItemType, Other>(with: NonEmptyList) -> NonEmptyList
	pair: <ItemType extends AnyType, Other extends AnyType>(self: ListType<ItemType>, argument1: ListType<Other>) => ListType<RecordType & { first: ItemType; second: Other }>
	// split<ItemType>(intoGroupsOf: Integer) -> NonEmptyList
	split: <ItemType extends AnyType>(self: ListType<ItemType>, intoGroupsOf: IntegerType) => ListType<ListType<ItemType>>
}

export type NonEmptyNestedListNatives = {
	// flatten<ItemType>() -> NonEmptyList
	flatten: <ItemType extends AnyType>(self: ListType<ListType<ItemType>>) => ListType<ItemType>
}

export type IntegerListNatives = {

}

export type RationalListNatives = {

}

export type NumberListNatives = {

}

export type NonEmptyIntegerListNatives = {

}

export type NonEmptyRationalListNatives = {

}

export type NonEmptyNumberListNatives = {

}

export type KeyedNumberListNatives = {

}

export type NonEmptyKeyedNumberListNatives = {

}

export type DictionaryNatives = {
	// static of<ValueType, KeyType is Equatable>(_: List<{ key: KeyType, value: ValueType }>) -> Dictionary<KeyType, ValueType>
	of: <ValueType extends AnyType, KeyType extends AnyType>(argument0: ListType<RecordType & { key: KeyType; value: ValueType }>, KeyType__conformance: EquatableConformance<KeyType>) => DictionaryType<KeyType, ValueType>
	// is<KeyType is Equatable, ValueType is Equatable>(_: Dictionary<KeyType, ValueType>) -> Boolean
	is: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>, argument1: DictionaryType<KeyType, ValueType>, KeyType__conformance: EquatableConformance<KeyType>, ValueType__conformance: EquatableConformance<ValueType>) => BooleanType
	// toString<KeyType is Printable, ValueType is Printable>() -> String
	toString: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>, KeyType__conformance: PrintableConformance<KeyType>, ValueType__conformance: PrintableConformance<ValueType>) => StringType
	// isEmpty<KeyType, ValueType>() -> Boolean
	isEmpty: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>) => BooleanType
	// length<KeyType, ValueType>() -> NonNegativeInteger
	length: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>) => IntegerType
	// value<ValueType, KeyType is Equatable>(at: KeyType) -> Optional<ValueType>
	value__overload$1: <ValueType extends AnyType, KeyType extends AnyType>(self: DictionaryType<KeyType, ValueType>, at: KeyType, KeyType__conformance: EquatableConformance<KeyType>) => OptionalType<ValueType>
	// keys<KeyType, ValueType>() -> List<KeyType>
	keys: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>) => ListType<KeyType>
	// values<KeyType, ValueType>() -> List<ValueType>
	values: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>) => ListType<ValueType>
	// entries<KeyType, ValueType>() -> List<{ key: KeyType, value: ValueType }>
	entries: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>) => ListType<RecordType & { key: KeyType; value: ValueType }>
	// set<ValueType, KeyType is Equatable>(_: KeyType, to: ValueType) -> NonEmptyDictionary
	set: <ValueType extends AnyType, KeyType extends AnyType>(self: DictionaryType<KeyType, ValueType>, argument1: KeyType, to: ValueType, KeyType__conformance: EquatableConformance<KeyType>) => DictionaryType<KeyType, ValueType>
	// remove<ValueType, KeyType is Equatable>(at: KeyType) -> Dictionary<KeyType, ValueType>
	remove: <ValueType extends AnyType, KeyType extends AnyType>(self: DictionaryType<KeyType, ValueType>, at: KeyType, KeyType__conformance: EquatableConformance<KeyType>) => DictionaryType<KeyType, ValueType>
	// removeEvery<KeyType, ValueType>(where: (_: { key: KeyType, value: ValueType }) -> Boolean) -> Dictionary<KeyType, ValueType>
	removeEvery: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>, where: (argument0: RecordType & { key: KeyType; value: ValueType }) => BooleanType) => DictionaryType<KeyType, ValueType>
	// everyEntry<KeyType, ValueType>(where: (_: { key: KeyType, value: ValueType }) -> Boolean) -> Dictionary<KeyType, ValueType>
	everyEntry: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>, where: (argument0: RecordType & { key: KeyType; value: ValueType }) => BooleanType) => DictionaryType<KeyType, ValueType>
	// map<KeyType, ValueType, Result>(_: (_: { key: KeyType, value: ValueType }) -> Result) -> Dictionary<KeyType, Result>
	map: <KeyType extends AnyType, ValueType extends AnyType, Result extends AnyType>(self: DictionaryType<KeyType, ValueType>, argument1: (argument0: RecordType & { key: KeyType; value: ValueType }) => Result) => DictionaryType<KeyType, Result>
}

export type NonEmptyDictionaryNatives = {
	// length<KeyType, ValueType>() -> PositiveInteger
	length: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>) => IntegerType
	// keys<KeyType, ValueType>() -> NonEmptyList
	keys: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>) => ListType<KeyType>
	// values<KeyType, ValueType>() -> NonEmptyList
	values: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>) => ListType<ValueType>
	// entries<KeyType, ValueType>() -> NonEmptyList
	entries: <KeyType extends AnyType, ValueType extends AnyType>(self: DictionaryType<KeyType, ValueType>) => ListType<RecordType & { key: KeyType; value: ValueType }>
	// map<KeyType, ValueType, Result>(_: (_: { key: KeyType, value: ValueType }) -> Result) -> NonEmptyDictionary
	map: <KeyType extends AnyType, ValueType extends AnyType, Result extends AnyType>(self: DictionaryType<KeyType, ValueType>, argument1: (argument0: RecordType & { key: KeyType; value: ValueType }) => Result) => DictionaryType<KeyType, Result>
}

export type GroupedListNatives = {
	// group<ItemType, Key is Equatable>(on: (_: ItemType) -> Key) -> Dictionary<Key, NonEmptyList>
	group: <ItemType extends AnyType, Key extends AnyType>(self: ListType<ItemType>, on: (argument0: ItemType) => Key, Key__conformance: EquatableConformance<Key>) => DictionaryType<Key, ListType<ItemType>>
	// tally<ItemType is Equatable>() -> Dictionary<ItemType, PositiveInteger>
	tally: <ItemType extends AnyType>(self: ListType<ItemType>, ItemType__conformance: EquatableConformance<ItemType>) => DictionaryType<ItemType, IntegerType>
	// index<ItemType, Key is Equatable>(on: (_: ItemType) -> Key) -> Dictionary<Key, ItemType>
	index: <ItemType extends AnyType, Key extends AnyType>(self: ListType<ItemType>, on: (argument0: ItemType) => Key, Key__conformance: EquatableConformance<Key>) => DictionaryType<Key, ItemType>
}

export type GroupedNonEmptyListNatives = {
	// group<ItemType, Key is Equatable>(on: (_: ItemType) -> Key) -> NonEmptyDictionary
	group: <ItemType extends AnyType, Key extends AnyType>(self: ListType<ItemType>, on: (argument0: ItemType) => Key, Key__conformance: EquatableConformance<Key>) => DictionaryType<Key, ListType<ItemType>>
	// tally<ItemType is Equatable>() -> NonEmptyDictionary
	tally: <ItemType extends AnyType>(self: ListType<ItemType>, ItemType__conformance: EquatableConformance<ItemType>) => DictionaryType<ItemType, IntegerType>
	// index<ItemType, Key is Equatable>(on: (_: ItemType) -> Key) -> NonEmptyDictionary
	index: <ItemType extends AnyType, Key extends AnyType>(self: ListType<ItemType>, on: (argument0: ItemType) => Key, Key__conformance: EquatableConformance<Key>) => DictionaryType<Key, ItemType>
}

export type RandomnessNatives = {
	// static entropy() -> Randomness
	entropy: () => RandomnessType
	// static seeded(_: String) -> Randomness
	seeded: (argument0: StringType) => RandomnessType
	// drawBoolean() -> Boolean
	drawBoolean__overload$1: (self: RandomnessType) => BooleanType
	// drawBoolean(withProbability: Rational) -> Boolean
	drawBoolean__overload$2: (self: RandomnessType, withProbability: RationalType) => BooleanType
	// drawInteger(between: Integer, and: Integer) -> Integer
	drawInteger__overload$1: (self: RandomnessType, between: IntegerType, and: IntegerType) => IntegerType
	// drawInteger(below: PositiveInteger) -> NonNegativeInteger
	drawInteger__overload$2: (self: RandomnessType, below: IntegerType) => IntegerType
	// drawRational(between: Rational, and: Rational) -> Rational
	drawRational__overload$1: (self: RandomnessType, between: RationalType, and: RationalType) => RationalType
	// drawRational(between: Rational, and: Rational, over: PositiveInteger) -> Rational
	drawRational__overload$2: (self: RandomnessType, between: RationalType, and: RationalType, over: IntegerType) => RationalType
	// drawString(upTo: Integer) -> String
	drawString: (self: RandomnessType, upTo: IntegerType) => StringType
	// pick<ItemType>(from: NonEmptyList) -> ItemType
	pick__overload$1: <ItemType extends AnyType>(self: RandomnessType, from: ListType<ItemType>) => ItemType
	// pick<ItemType>(_: PositiveInteger, from: NonEmptyList) -> NonEmptyList
	pick__overload$2: <ItemType extends AnyType>(self: RandomnessType, argument1: IntegerType, from: ListType<ItemType>) => ListType<ItemType>
	// pick<ItemType>(from: NonEmptyList, weightedBy: (_: ItemType) -> Rational) -> ItemType
	pick__overload$3: <ItemType extends AnyType>(self: RandomnessType, from: ListType<ItemType>, weightedBy: (argument0: ItemType) => RationalType) => ItemType
	// shuffle<ItemType>(_: List<ItemType>) -> List<ItemType>
	shuffle__overload$1: <ItemType extends AnyType>(self: RandomnessType, argument1: ListType<ItemType>) => ListType<ItemType>
	// shuffle<ItemType>(_: NonEmptyList) -> NonEmptyList
	shuffle__overload$2: <ItemType extends AnyType>(self: RandomnessType, argument1: ListType<ItemType>) => ListType<ItemType>
}

export type FunctionsNatives = {
	// static loop<State>(startingWith: State, while: (_: State) -> Boolean, step: (_: State) -> State) -> State
	loop__overload$1: <State extends AnyType>(startingWith: State, argument1: (argument0: State) => BooleanType, step: (argument0: State) => State) => State
	// static loop<State, Result>(startingWith: State, step: (_: State) -> Step<State, Result>) -> Result
	loop__overload$4: <State extends AnyType, Result extends AnyType>(startingWith: State, step: (argument0: State) => StepType<State, Result>) => Result
}

declare const TerminalModule: typeof import("./Terminal")
export const $Terminal: TerminalNatives = TerminalModule
export const $TerminalAbsent: AssertNoEssenceExports<typeof import("./Terminal"), "print"> = true
export const $TerminalArity: AssertArities<typeof import("./Terminal"), {
	write: 2
	inspect: 1
	describe: 1
}> = true

declare const StringModule: typeof import("./String")
export const $String: StringNatives = StringModule
export const $StringAbsent: AssertNoEssenceExports<typeof import("./String"), "is__overload$1" | "is__overload$2" | "compare__overload$2" | "toString" | "isEmpty" | "hasCharacters" | "contains" | "doesNotContain" | "starts" | "doesNotStart" | "doesNotEnd" | "lines" | "characters" | "character__overload$2" | "firstIndex__overload$2" | "lastIndex__overload$2" | "firstCharacter__overload$1" | "firstCharacter__overload$2" | "lastCharacter__overload$1" | "lastCharacter__overload$2" | "prepend" | "replaceEvery" | "replaceFirst" | "pad"> = true
export const $StringArity: AssertArities<typeof import("./String"), {
	compare__overload$1: 2
	ends: 2
	words: 1
	length: 1
	character__overload$1: 2
	firstIndex__overload$1: 2
	lastIndex__overload$1: 2
	append: 2
	split__overload$1: 2
	split__overload$2: 2
	count: 2
	uppercase: 1
	lowercase: 1
	normalize: 2
	trim: 2
	repeat: 2
	reverse: 1
	slice: 3
}> = true

declare const NonEmptyStringModule: typeof import("./NonEmptyString")
export const $NonEmptyString: NonEmptyStringNatives = NonEmptyStringModule
export const $NonEmptyStringArity: AssertArities<typeof import("./NonEmptyString"), {
	length: 1
	characters: 1
	firstCharacter: 1
	lastCharacter: 1
	uppercase: 1
	lowercase: 1
	reverse: 1
	repeat: 2
}> = true

declare const BooleanModule: typeof import("./Boolean")
export const $Boolean: BooleanNatives = BooleanModule
export const $BooleanAbsent: AssertNoEssenceExports<typeof import("./Boolean"), "toString" | "exclusiveOr"> = true
export const $BooleanArity: AssertArities<typeof import("./Boolean"), {
	is: 2
	negate: 1
	and: 2
	or: 2
}> = true

declare const IntegerModule: typeof import("./Integer")
export const $Integer: IntegerNatives = IntegerModule
export const $IntegerAbsent: AssertNoEssenceExports<typeof import("./Integer"), "parse__overload$1" | "parse__overload$2" | "is__overload$1" | "is__overload$2" | "isNot__overload$1" | "isNot__overload$2" | "add__overload$2" | "add__overload$3" | "add__overload$4" | "subtract__overload$1" | "subtract__overload$2" | "subtract__overload$3" | "subtract__overload$4" | "multiply__overload$2" | "multiply__overload$3" | "multiply__overload$4" | "divide__overload$1" | "divide__overload$2" | "divide__overload$5" | "divide__overload$6" | "divide__overload$7" | "remainder__overload$3" | "quotient__overload$3" | "raise__overload$2" | "squareRoot__overload$2" | "isLessThan__overload$1" | "isLessThan__overload$2" | "isLessThanOrEqualTo__overload$1" | "isLessThanOrEqualTo__overload$2" | "isGreaterThan__overload$1" | "isGreaterThan__overload$2" | "isGreaterThanOrEqualTo__overload$1" | "isGreaterThanOrEqualTo__overload$2" | "isEven" | "isOdd" | "isPositive" | "isNegative" | "isZero" | "isWholeNumber" | "isMultiple" | "round"> = true
export const $IntegerArity: AssertArities<typeof import("./Integer"), {
	compare: 2
	toString: 1
	add__overload$1: 2
	multiply__overload$1: 2
	divide__overload$3: 2
	divide__overload$4: 2
	remainder__overload$1: 2
	remainder__overload$2: 2
	quotient__overload$1: 2
	quotient__overload$2: 2
	raise__overload$1: 2
	raise__overload$3: 2
	squareRoot__overload$1: 1
	absolute: 1
	negate: 1
}> = true

declare const NonZeroIntegerModule: typeof import("./NonZeroInteger")
export const $NonZeroInteger: NonZeroIntegerNatives = NonZeroIntegerModule
export const $NonZeroIntegerAbsent: AssertNoEssenceExports<typeof import("./NonZeroInteger"), "multiply__overload$2" | "multiply__overload$3"> = true
export const $NonZeroIntegerArity: AssertArities<typeof import("./NonZeroInteger"), {
	multiply__overload$1: 2
	divide: 2
	raise__overload$1: 2
	raise__overload$2: 2
	absolute: 1
	negate: 1
}> = true

declare const NonNegativeIntegerModule: typeof import("./NonNegativeInteger")
export const $NonNegativeInteger: NonNegativeIntegerNatives = NonNegativeIntegerModule
export const $NonNegativeIntegerArity: AssertArities<typeof import("./NonNegativeInteger"), {
	add__overload$1: 2
	add__overload$2: 2
	multiply: 2
	squareRoot: 1
}> = true

declare const PositiveIntegerModule: typeof import("./PositiveInteger")
export const $PositiveInteger: PositiveIntegerNatives = PositiveIntegerModule
export const $PositiveIntegerArity: AssertArities<typeof import("./PositiveInteger"), {
	add: 2
	multiply: 2
	raise: 2
	squareRoot: 1
}> = true

declare const RationalModule: typeof import("./Rational")
export const $Rational: RationalNatives = RationalModule
export const $RationalAbsent: AssertNoEssenceExports<typeof import("./Rational"), "of__overload$3" | "parse__overload$1" | "parse__overload$2" | "is__overload$1" | "is__overload$2" | "isNot__overload$1" | "isNot__overload$2" | "toString__overload$1" | "add__overload$2" | "add__overload$3" | "add__overload$4" | "subtract__overload$2" | "subtract__overload$3" | "subtract__overload$4" | "multiply__overload$2" | "multiply__overload$3" | "multiply__overload$4" | "divide__overload$2" | "divide__overload$4" | "divide__overload$5" | "divide__overload$6" | "raise__overload$2" | "squareRoot__overload$2" | "isLessThan__overload$1" | "isLessThan__overload$2" | "isLessThanOrEqualTo__overload$1" | "isLessThanOrEqualTo__overload$2" | "isGreaterThan__overload$1" | "isGreaterThan__overload$2" | "isGreaterThanOrEqualTo__overload$1" | "isGreaterThanOrEqualTo__overload$2" | "isWholeNumber" | "isPositive" | "isNegative" | "isZero" | "absolute" | "negate" | "reciprocal__overload$1" | "reciprocal__overload$2" | "round__overload$1" | "round__overload$2"> = true
export const $RationalArity: AssertArities<typeof import("./Rational"), {
	of__overload$1: 2
	of__overload$2: 2
	compare: 2
	toString__overload$2: 2
	toString__overload$3: 3
	add__overload$1: 2
	subtract__overload$1: 2
	multiply__overload$1: 2
	divide__overload$1: 2
	divide__overload$3: 2
	divide__overload$7: 2
	raise__overload$1: 2
	raise__overload$3: 2
	squareRoot__overload$1: 1
	numerator: 1
	denominator: 1
}> = true

declare const NonZeroRationalModule: typeof import("./NonZeroRational")
export const $NonZeroRational: NonZeroRationalNatives = NonZeroRationalModule
export const $NonZeroRationalAbsent: AssertNoEssenceExports<typeof import("./NonZeroRational"), "absolute"> = true
export const $NonZeroRationalArity: AssertArities<typeof import("./NonZeroRational"), {
	multiply: 2
	numerator: 1
	reciprocal: 1
	negate: 1
}> = true

declare const ScalarModule: typeof import("./Scalar")
export const $Scalar: ScalarNatives = ScalarModule
export const $ScalarAbsent: AssertNoEssenceExports<typeof import("./Scalar"), "add" | "multiply"> = true

declare const AlgebraicModule: typeof import("./Algebraic")
export const $Algebraic: AlgebraicNatives = AlgebraicModule
export const $AlgebraicAbsent: AssertNoEssenceExports<typeof import("./Algebraic"), "is" | "add__overload$4" | "subtract__overload$1" | "subtract__overload$2" | "subtract__overload$3" | "subtract__overload$4" | "multiply__overload$4" | "divide__overload$4" | "divide__overload$5" | "divide__overload$6" | "isPositive" | "isNegative" | "absolute"> = true
export const $AlgebraicArity: AssertArities<typeof import("./Algebraic"), {
	compare: 2
	toString: 1
	add__overload$1: 2
	add__overload$2: 2
	add__overload$3: 2
	multiply__overload$1: 2
	multiply__overload$2: 2
	multiply__overload$3: 2
	multiply__overload$5: 2
	multiply__overload$6: 2
	divide__overload$1: 2
	divide__overload$2: 2
	divide__overload$3: 2
	divide__overload$7: 2
	divide__overload$8: 2
	negate: 1
}> = true

declare const TranscendentalModule: typeof import("./Transcendental")
export const $Transcendental: TranscendentalNatives = TranscendentalModule
export const $TranscendentalAbsent: AssertNoEssenceExports<typeof import("./Transcendental"), "subtract__overload$1" | "subtract__overload$2" | "subtract__overload$3" | "divide__overload$4" | "divide__overload$5" | "divide__overload$6"> = true
export const $TranscendentalArity: AssertArities<typeof import("./Transcendental"), {
	is: 2
	compare: 3
	toString: 1
	add__overload$1: 2
	add__overload$2: 2
	add__overload$3: 2
	multiply__overload$1: 2
	multiply__overload$2: 2
	multiply__overload$3: 2
	multiply__overload$4: 2
	divide__overload$1: 2
	divide__overload$2: 2
	divide__overload$3: 2
	divide__overload$7: 2
	divide__overload$8: 2
	absolute: 1
	negate: 1
}> = true

declare const NumberModule: typeof import("./Number")
export const $Number: NumberNatives = NumberModule
export const $NumberAbsent: AssertNoEssenceExports<typeof import("./Number"), "sum__overload$1" | "sum__overload$2" | "sum__overload$3" | "product__overload$1" | "product__overload$2" | "product__overload$3" | "average__overload$1" | "average__overload$2" | "average__overload$3" | "average__overload$4" | "average__overload$5" | "average__overload$6" | "average__overload$7" | "average__overload$8" | "average__overload$9" | "lowestNumber__overload$1" | "lowestNumber__overload$2" | "lowestNumber__overload$3" | "lowestNumber__overload$4" | "lowestNumber__overload$5" | "lowestNumber__overload$6" | "lowestNumber__overload$7" | "lowestNumber__overload$8" | "lowestNumber__overload$9" | "lowestNumber__overload$10" | "lowestNumber__overload$11" | "lowestNumber__overload$12" | "lowestNumber__overload$13" | "highestNumber__overload$1" | "highestNumber__overload$2" | "highestNumber__overload$3" | "highestNumber__overload$4" | "highestNumber__overload$5" | "highestNumber__overload$6" | "highestNumber__overload$7" | "highestNumber__overload$8" | "highestNumber__overload$9" | "highestNumber__overload$10" | "highestNumber__overload$11" | "highestNumber__overload$12" | "highestNumber__overload$13" | "is" | "toString"> = true
export const $NumberArity: AssertArities<typeof import("./Number"), {
	compare: 2
}> = true

declare const OptionalModule: typeof import("./Optional")
export const $Optional: OptionalNatives = OptionalModule
export const $OptionalAbsent: AssertNoEssenceExports<typeof import("./Optional"), "is__overload$1" | "is__overload$2" | "isNot__overload$1" | "isNot__overload$2" | "hasValue" | "isEmpty" | "value" | "map" | "andThen" | "keep"> = true
export const $OptionalArity: AssertArities<typeof import("./Optional"), {
	toString: 2
}> = true

declare const NestedOptionalModule: typeof import("./NestedOptional")
export const $NestedOptional: NestedOptionalNatives = NestedOptionalModule
export const $NestedOptionalAbsent: AssertNoEssenceExports<typeof import("./NestedOptional"), "flatten"> = true

declare const OrderingModule: typeof import("./Ordering")
export const $Ordering: OrderingNatives = OrderingModule

declare const SideModule: typeof import("./Side")
export const $Side: SideNatives = SideModule

declare const CaseSensitivityModule: typeof import("./CaseSensitivity")
export const $CaseSensitivity: CaseSensitivityNatives = CaseSensitivityModule

declare const NormalizationFormModule: typeof import("./NormalizationForm")
export const $NormalizationForm: NormalizationFormNatives = NormalizationFormModule

declare const NumberFormatModule: typeof import("./NumberFormat")
export const $NumberFormat: NumberFormatNatives = NumberFormatModule

declare const RoundingModule: typeof import("./Rounding")
export const $Rounding: RoundingNatives = RoundingModule

declare const SortOrderModule: typeof import("./SortOrder")
export const $SortOrder: SortOrderNatives = SortOrderModule

declare const StreamModule: typeof import("./Stream")
export const $Stream: StreamNatives = StreamModule

declare const RecordModule: typeof import("./Record")
export const $Record: RecordNatives = RecordModule
export const $RecordArity: AssertArities<typeof import("./Record"), {
	is: 2
	toString: 1
	keys: 1
}> = true

declare const ListModule: typeof import("./List")
export const $List: ListNatives = ListModule
export const $ListAbsent: AssertNoEssenceExports<typeof import("./List"), "repeat__overload$1" | "of__overload$2" | "hasItems__overload$1" | "hasItems__overload$2" | "isEmpty" | "contains" | "doesNotContain" | "hasOnlyItems" | "hasNoItems" | "firstItem__overload$1" | "firstItem__overload$2" | "firstItem__overload$3" | "firstItem__overload$4" | "lastItem__overload$1" | "lastItem__overload$2" | "lastItem__overload$3" | "lastItem__overload$4" | "item__overload$2" | "firstIndex__overload$1" | "firstIndex__overload$2" | "firstIndex__overload$3" | "firstIndex__overload$4" | "lastIndex__overload$1" | "lastIndex__overload$2" | "lastIndex__overload$4" | "indices" | "removeFirst" | "removeEvery__overload$1" | "removeEvery__overload$2" | "removeLast" | "prepend__overload$2" | "count__overload$1" | "count__overload$2" | "replace__overload$1" | "replace__overload$2" | "lowestItem__overload$1" | "lowestItem__overload$2" | "highestItem__overload$1" | "highestItem__overload$2" | "firstItems" | "lastItems"> = true
export const $ListArity: AssertArities<typeof import("./List"), {
	repeat__overload$2: 2
	of__overload$1: 2
	is: 3
	compare: 3
	toString: 2
	length: 1
	item__overload$1: 2
	lastIndex__overload$3: 2
	enumerate: 1
	remove: 2
	prepend__overload$1: 2
	append__overload$1: 2
	append__overload$2: 2
	map: 2
	reduce__overload$1: 3
	reduce__overload$2: 3
	everyItem: 2
	slice: 3
	reverse: 1
	sort__overload$1: 3
	sort__overload$2: 2
	sort__overload$3: 4
	insert: 3
	join: 3
	partition: 2
	pair: 2
	split: 2
}> = true

declare const NestedListModule: typeof import("./NestedList")
export const $NestedList: NestedListNatives = NestedListModule
export const $NestedListArity: AssertArities<typeof import("./NestedList"), {
	flatten: 1
}> = true

declare const OptionalListModule: typeof import("./OptionalList")
export const $OptionalList: OptionalListNatives = OptionalListModule
export const $OptionalListAbsent: AssertNoEssenceExports<typeof import("./OptionalList"), "values"> = true

declare const NonEmptyListModule: typeof import("./NonEmptyList")
export const $NonEmptyList: NonEmptyListNatives = NonEmptyListModule
export const $NonEmptyListAbsent: AssertNoEssenceExports<typeof import("./NonEmptyList"), "indices" | "replace__overload$2" | "lowestItem" | "highestItem"> = true
export const $NonEmptyListArity: AssertArities<typeof import("./NonEmptyList"), {
	firstItem: 1
	lastItem: 1
	length: 1
	enumerate: 1
	prepend: 2
	append: 2
	map: 2
	reverse: 1
	sort__overload$1: 3
	sort__overload$2: 2
	sort__overload$3: 4
	replace__overload$1: 3
	pair: 2
	split: 2
}> = true

declare const NonEmptyNestedListModule: typeof import("./NonEmptyNestedList")
export const $NonEmptyNestedList: NonEmptyNestedListNatives = NonEmptyNestedListModule
export const $NonEmptyNestedListArity: AssertArities<typeof import("./NonEmptyNestedList"), {
	flatten: 1
}> = true

declare const IntegerListModule: typeof import("./IntegerList")
export const $IntegerList: IntegerListNatives = IntegerListModule
export const $IntegerListAbsent: AssertNoEssenceExports<typeof import("./IntegerList"), "sum" | "product" | "average__overload$1" | "average__overload$2" | "lowestNumber__overload$1" | "lowestNumber__overload$2" | "highestNumber__overload$1" | "highestNumber__overload$2"> = true

declare const RationalListModule: typeof import("./RationalList")
export const $RationalList: RationalListNatives = RationalListModule
export const $RationalListAbsent: AssertNoEssenceExports<typeof import("./RationalList"), "sum" | "product" | "average__overload$1" | "average__overload$2" | "lowestNumber__overload$1" | "lowestNumber__overload$2" | "highestNumber__overload$1" | "highestNumber__overload$2"> = true

declare const NumberListModule: typeof import("./NumberList")
export const $NumberList: NumberListNatives = NumberListModule
export const $NumberListAbsent: AssertNoEssenceExports<typeof import("./NumberList"), "sum" | "product" | "average__overload$1" | "average__overload$2" | "lowestNumber__overload$1" | "lowestNumber__overload$2" | "highestNumber__overload$1" | "highestNumber__overload$2"> = true

declare const NonEmptyIntegerListModule: typeof import("./NonEmptyIntegerList")
export const $NonEmptyIntegerList: NonEmptyIntegerListNatives = NonEmptyIntegerListModule
export const $NonEmptyIntegerListAbsent: AssertNoEssenceExports<typeof import("./NonEmptyIntegerList"), "lowestNumber" | "highestNumber" | "average"> = true

declare const NonEmptyRationalListModule: typeof import("./NonEmptyRationalList")
export const $NonEmptyRationalList: NonEmptyRationalListNatives = NonEmptyRationalListModule
export const $NonEmptyRationalListAbsent: AssertNoEssenceExports<typeof import("./NonEmptyRationalList"), "lowestNumber" | "highestNumber" | "average"> = true

declare const NonEmptyNumberListModule: typeof import("./NonEmptyNumberList")
export const $NonEmptyNumberList: NonEmptyNumberListNatives = NonEmptyNumberListModule
export const $NonEmptyNumberListAbsent: AssertNoEssenceExports<typeof import("./NonEmptyNumberList"), "lowestNumber" | "highestNumber" | "average"> = true

declare const KeyedNumberListModule: typeof import("./KeyedNumberList")
export const $KeyedNumberList: KeyedNumberListNatives = KeyedNumberListModule
export const $KeyedNumberListAbsent: AssertNoEssenceExports<typeof import("./KeyedNumberList"), "sum__overload$1" | "sum__overload$2" | "sum__overload$3" | "average__overload$1" | "average__overload$2"> = true

declare const NonEmptyKeyedNumberListModule: typeof import("./NonEmptyKeyedNumberList")
export const $NonEmptyKeyedNumberList: NonEmptyKeyedNumberListNatives = NonEmptyKeyedNumberListModule
export const $NonEmptyKeyedNumberListAbsent: AssertNoEssenceExports<typeof import("./NonEmptyKeyedNumberList"), "average"> = true

declare const DictionaryModule: typeof import("./Dictionary")
export const $Dictionary: DictionaryNatives = DictionaryModule
export const $DictionaryAbsent: AssertNoEssenceExports<typeof import("./Dictionary"), "hasEntries__overload$1" | "hasEntries__overload$2" | "hasKey" | "value__overload$2" | "update__overload$1" | "update__overload$2" | "merge__overload$1" | "merge__overload$2"> = true
export const $DictionaryArity: AssertArities<typeof import("./Dictionary"), {
	of: 2
	is: 4
	toString: 3
	isEmpty: 1
	length: 1
	value__overload$1: 3
	keys: 1
	values: 1
	entries: 1
	set: 4
	remove: 3
	removeEvery: 2
	everyEntry: 2
	map: 2
}> = true

declare const NonEmptyDictionaryModule: typeof import("./NonEmptyDictionary")
export const $NonEmptyDictionary: NonEmptyDictionaryNatives = NonEmptyDictionaryModule
export const $NonEmptyDictionaryArity: AssertArities<typeof import("./NonEmptyDictionary"), {
	length: 1
	keys: 1
	values: 1
	entries: 1
	map: 2
}> = true

declare const GroupedListModule: typeof import("./GroupedList")
export const $GroupedList: GroupedListNatives = GroupedListModule
export const $GroupedListAbsent: AssertNoEssenceExports<typeof import("./GroupedList"), "removeDuplicates"> = true
export const $GroupedListArity: AssertArities<typeof import("./GroupedList"), {
	group: 3
	tally: 2
	index: 3
}> = true

declare const GroupedNonEmptyListModule: typeof import("./GroupedNonEmptyList")
export const $GroupedNonEmptyList: GroupedNonEmptyListNatives = GroupedNonEmptyListModule
export const $GroupedNonEmptyListAbsent: AssertNoEssenceExports<typeof import("./GroupedNonEmptyList"), "removeDuplicates"> = true
export const $GroupedNonEmptyListArity: AssertArities<typeof import("./GroupedNonEmptyList"), {
	group: 3
	tally: 2
	index: 3
}> = true

declare const RandomnessModule: typeof import("./Randomness")
export const $Randomness: RandomnessNatives = RandomnessModule
export const $RandomnessArity: AssertArities<typeof import("./Randomness"), {
	entropy: 0
	seeded: 1
	drawBoolean__overload$1: 1
	drawBoolean__overload$2: 2
	drawInteger__overload$1: 3
	drawInteger__overload$2: 2
	drawRational__overload$1: 3
	drawRational__overload$2: 4
	drawString: 2
	pick__overload$1: 2
	pick__overload$2: 3
	pick__overload$3: 3
	shuffle__overload$1: 2
	shuffle__overload$2: 2
}> = true

declare const functionsModule: typeof import("./functions")
export const $functions: FunctionsNatives = functionsModule
export const $functionsAbsent: AssertNoEssenceExports<typeof import("./functions"), "loop__overload$2" | "loop__overload$3" | "loop__overload$5"> = true
export const $functionsArity: AssertArities<typeof import("./functions"), {
	loop__overload$1: 3
	loop__overload$4: 2
}> = true
